FROM {{ docker_sonic_mgmt_framework_load_image }}

ARG docker_container_name
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN pip install python_dateutil==2.6.0\
                setuptools==21.0.0 \
                grpcio-tools==1.20.0 \
                pyangbind==0.6.0 \
                certifi==2017.4.17 \
                python-dateutil==2.6.0 \
                six==1.11.0 \
                urllib3==1.21.1 \
                requests==2.20.0 \
                simplejson==3.8.0 \
                distribute==0.7.3 \
                unittest2==1.1.0


#RUN apt-get install -f -y libdbus-1-3 libdaemon0 libjansson4
RUN apt-get install -f -y libatomic1 liblua5.1-0 lua-bitop lua-cjson

## Install redis-tools dependencies
## TODO: implicitly install dependencies
RUN apt-get -y install libjemalloc1 libdbus-c++-1-0v5 libdbus-1-3 openssl

COPY \
{% for deb in docker_sonic_mgmt_framework_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor -%}
debs/

RUN dpkg -i \
{% for deb in docker_sonic_mgmt_framework_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor %}

COPY ["mk-root-ca.sh", "/usr/sbin/"]
COPY ["ca.conf", "/etc/"]
COPY ["start.sh", "rest-server.sh", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]

RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y
RUN rm -rf /debs

#RUN ln -sf /host_etc/passwd /etc/passwd
#RUN ln -sf /host_etc/group /etc/group

ENTRYPOINT ["/usr/bin/supervisord"]
