# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from sonic_interface_client.models.sonic_interface_sonic_interface_interface_interface_list import SonicInterfaceSonicInterfaceInterfaceInterfaceList  # noqa: F401,E501
from sonic_interface_client.models.sonic_interface_sonic_interface_sonicinterfacesonicinterface_interfaceinterfacelist import SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceINTERFACEINTERFACELIST  # noqa: F401,E501


class PutListSonicInterfaceSonicInterfaceInterfaceInterfaceList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sonic_interface_interface_list': 'list[SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceINTERFACEINTERFACELIST]'
    }

    attribute_map = {
        'sonic_interface_interface_list': 'sonic-interface:INTERFACE_LIST'
    }

    def __init__(self, sonic_interface_interface_list=None):  # noqa: E501
        """PutListSonicInterfaceSonicInterfaceInterfaceInterfaceList - a model defined in Swagger"""  # noqa: E501

        self._sonic_interface_interface_list = None
        self.discriminator = None

        if sonic_interface_interface_list is not None:
            self.sonic_interface_interface_list = sonic_interface_interface_list

    @property
    def sonic_interface_interface_list(self):
        """Gets the sonic_interface_interface_list of this PutListSonicInterfaceSonicInterfaceInterfaceInterfaceList.  # noqa: E501


        :return: The sonic_interface_interface_list of this PutListSonicInterfaceSonicInterfaceInterfaceInterfaceList.  # noqa: E501
        :rtype: list[SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceINTERFACEINTERFACELIST]
        """
        return self._sonic_interface_interface_list

    @sonic_interface_interface_list.setter
    def sonic_interface_interface_list(self, sonic_interface_interface_list):
        """Sets the sonic_interface_interface_list of this PutListSonicInterfaceSonicInterfaceInterfaceInterfaceList.


        :param sonic_interface_interface_list: The sonic_interface_interface_list of this PutListSonicInterfaceSonicInterfaceInterfaceInterfaceList.  # noqa: E501
        :type: list[SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceINTERFACEINTERFACELIST]
        """

        self._sonic_interface_interface_list = sonic_interface_interface_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PutListSonicInterfaceSonicInterfaceInterfaceInterfaceList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PutListSonicInterfaceSonicInterfaceInterfaceInterfaceList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
