#!/bin/bash

# Set the max arp and max ndp entries in the proc settings

echo 32000 > /proc/sys/net/ipv4/neigh/default/gc_thresh1
echo 48000 > /proc/sys/net/ipv4/neigh/default/gc_thresh2
echo 64000 > /proc/sys/net/ipv4/neigh/default/gc_thresh3
echo 16000 > /proc/sys/net/ipv6/neigh/default/gc_thresh1
echo 32000 > /proc/sys/net/ipv6/neigh/default/gc_thresh2
echo 48000 > /proc/sys/net/ipv6/neigh/default/gc_thresh3
