#!/bin/sh

QUEUE=/tmp/dpkgd-queue
if mkdir $QUEUE 2>/dev/null
then
	echo Starting dpkgd
	./dpkgd $QUEUE&
fi

# reserve the filename
cd /tmp
MKTEMP=`mktemp -p .`

#Add to queue
cd $QUEUE
echo $*>$MKTEMP

i=1200
while [ $i -gt 0 ]
do
	if [ ! -f $MKTEMP ]
	then
		# Remove reservation
		rm /tmp/$MKTEMP
		exit
	fi
	sleep 1
	i=`expr $i - 1`
done

exit 18
