# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.acl_openconfigaclacl_aclsets_aclentries import AclOpenconfigaclaclAclsetsAclentries  # noqa: F401,E501
from swagger_server.models.acl_openconfigaclacl_aclsets_config import AclOpenconfigaclaclAclsetsConfig  # noqa: F401,E501
from swagger_server import util


class AclOpenconfigaclaclAclsetsAclset(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, type: str=None, config: AclOpenconfigaclaclAclsetsConfig=None, acl_entries: AclOpenconfigaclaclAclsetsAclentries=None):  # noqa: E501
        """AclOpenconfigaclaclAclsetsAclset - a model defined in Swagger

        :param name: The name of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501
        :type name: str
        :param type: The type of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501
        :type type: str
        :param config: The config of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501
        :type config: AclOpenconfigaclaclAclsetsConfig
        :param acl_entries: The acl_entries of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501
        :type acl_entries: AclOpenconfigaclaclAclsetsAclentries
        """
        self.swagger_types = {
            'name': str,
            'type': str,
            'config': AclOpenconfigaclaclAclsetsConfig,
            'acl_entries': AclOpenconfigaclaclAclsetsAclentries
        }

        self.attribute_map = {
            'name': 'name',
            'type': 'type',
            'config': 'config',
            'acl_entries': 'acl-entries'
        }

        self._name = name
        self._type = type
        self._config = config
        self._acl_entries = acl_entries

    @classmethod
    def from_dict(cls, dikt) -> 'AclOpenconfigaclaclAclsetsAclset':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The acl_openconfigaclacl_aclsets_aclset of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501
        :rtype: AclOpenconfigaclaclAclsetsAclset
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this AclOpenconfigaclaclAclsetsAclset.


        :return: The name of this AclOpenconfigaclaclAclsetsAclset.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AclOpenconfigaclaclAclsetsAclset.


        :param name: The name of this AclOpenconfigaclaclAclsetsAclset.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self) -> str:
        """Gets the type of this AclOpenconfigaclaclAclsetsAclset.


        :return: The type of this AclOpenconfigaclaclAclsetsAclset.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this AclOpenconfigaclaclAclsetsAclset.


        :param type: The type of this AclOpenconfigaclaclAclsetsAclset.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def config(self) -> AclOpenconfigaclaclAclsetsConfig:
        """Gets the config of this AclOpenconfigaclaclAclsetsAclset.


        :return: The config of this AclOpenconfigaclaclAclsetsAclset.
        :rtype: AclOpenconfigaclaclAclsetsConfig
        """
        return self._config

    @config.setter
    def config(self, config: AclOpenconfigaclaclAclsetsConfig):
        """Sets the config of this AclOpenconfigaclaclAclsetsAclset.


        :param config: The config of this AclOpenconfigaclaclAclsetsAclset.
        :type config: AclOpenconfigaclaclAclsetsConfig
        """

        self._config = config

    @property
    def acl_entries(self) -> AclOpenconfigaclaclAclsetsAclentries:
        """Gets the acl_entries of this AclOpenconfigaclaclAclsetsAclset.


        :return: The acl_entries of this AclOpenconfigaclaclAclsetsAclset.
        :rtype: AclOpenconfigaclaclAclsetsAclentries
        """
        return self._acl_entries

    @acl_entries.setter
    def acl_entries(self, acl_entries: AclOpenconfigaclaclAclsetsAclentries):
        """Sets the acl_entries of this AclOpenconfigaclaclAclsetsAclset.


        :param acl_entries: The acl_entries of this AclOpenconfigaclaclAclsetsAclset.
        :type acl_entries: AclOpenconfigaclaclAclsetsAclentries
        """

        self._acl_entries = acl_entries
