# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.acl_acl_sets_acl_set_openconfigaclaclset import AclAclSetsAclSetOpenconfigaclaclset  # noqa: F401,E501
from swagger_server import util


class AclAclSetsAclSet(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, openconfig_aclacl_set: AclAclSetsAclSetOpenconfigaclaclset=None):  # noqa: E501
        """AclAclSetsAclSet - a model defined in Swagger

        :param openconfig_aclacl_set: The openconfig_aclacl_set of this AclAclSetsAclSet.  # noqa: E501
        :type openconfig_aclacl_set: AclAclSetsAclSetOpenconfigaclaclset
        """
        self.swagger_types = {
            'openconfig_aclacl_set': AclAclSetsAclSetOpenconfigaclaclset
        }

        self.attribute_map = {
            'openconfig_aclacl_set': 'openconfig-acl:acl-set'
        }

        self._openconfig_aclacl_set = openconfig_aclacl_set

    @classmethod
    def from_dict(cls, dikt) -> 'AclAclSetsAclSet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The acl_acl_sets_acl_set of this AclAclSetsAclSet.  # noqa: E501
        :rtype: AclAclSetsAclSet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def openconfig_aclacl_set(self) -> AclAclSetsAclSetOpenconfigaclaclset:
        """Gets the openconfig_aclacl_set of this AclAclSetsAclSet.


        :return: The openconfig_aclacl_set of this AclAclSetsAclSet.
        :rtype: AclAclSetsAclSetOpenconfigaclaclset
        """
        return self._openconfig_aclacl_set

    @openconfig_aclacl_set.setter
    def openconfig_aclacl_set(self, openconfig_aclacl_set: AclAclSetsAclSetOpenconfigaclaclset):
        """Sets the openconfig_aclacl_set of this AclAclSetsAclSet.


        :param openconfig_aclacl_set: The openconfig_aclacl_set of this AclAclSetsAclSet.
        :type openconfig_aclacl_set: AclAclSetsAclSetOpenconfigaclaclset
        """

        self._openconfig_aclacl_set = openconfig_aclacl_set
