# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ConfigSourceMac(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, source_mac: str=None):  # noqa: E501
        """ConfigSourceMac - a model defined in Swagger

        :param source_mac: The source_mac of this ConfigSourceMac.  # noqa: E501
        :type source_mac: str
        """
        self.swagger_types = {
            'source_mac': str
        }

        self.attribute_map = {
            'source_mac': 'source-mac'
        }

        self._source_mac = source_mac

    @classmethod
    def from_dict(cls, dikt) -> 'ConfigSourceMac':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The config_source_mac of this ConfigSourceMac.  # noqa: E501
        :rtype: ConfigSourceMac
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source_mac(self) -> str:
        """Gets the source_mac of this ConfigSourceMac.


        :return: The source_mac of this ConfigSourceMac.
        :rtype: str
        """
        return self._source_mac

    @source_mac.setter
    def source_mac(self, source_mac: str):
        """Sets the source_mac of this ConfigSourceMac.


        :param source_mac: The source_mac of this ConfigSourceMac.
        :type source_mac: str
        """

        self._source_mac = source_mac
