# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GetAclEntriesAclEntryStateMatchedPackets(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, matched_packets: int=None):  # noqa: E501
        """GetAclEntriesAclEntryStateMatchedPackets - a model defined in Swagger

        :param matched_packets: The matched_packets of this GetAclEntriesAclEntryStateMatchedPackets.  # noqa: E501
        :type matched_packets: int
        """
        self.swagger_types = {
            'matched_packets': int
        }

        self.attribute_map = {
            'matched_packets': 'matched-packets'
        }

        self._matched_packets = matched_packets

    @classmethod
    def from_dict(cls, dikt) -> 'GetAclEntriesAclEntryStateMatchedPackets':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_acl_entries_acl_entry_state_matched_packets of this GetAclEntriesAclEntryStateMatchedPackets.  # noqa: E501
        :rtype: GetAclEntriesAclEntryStateMatchedPackets
        """
        return util.deserialize_model(dikt, cls)

    @property
    def matched_packets(self) -> int:
        """Gets the matched_packets of this GetAclEntriesAclEntryStateMatchedPackets.


        :return: The matched_packets of this GetAclEntriesAclEntryStateMatchedPackets.
        :rtype: int
        """
        return self._matched_packets

    @matched_packets.setter
    def matched_packets(self, matched_packets: int):
        """Sets the matched_packets of this GetAclEntriesAclEntryStateMatchedPackets.


        :param matched_packets: The matched_packets of this GetAclEntriesAclEntryStateMatchedPackets.
        :type matched_packets: int
        """

        self._matched_packets = matched_packets
