# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_acl_openconfigaclacl_interfaces_interface import GetAclOpenconfigaclaclInterfacesInterface  # noqa: F401,E501
from swagger_server import util


class GetListBaseInterfacesInterface(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, openconfig_aclinterface: List[GetAclOpenconfigaclaclInterfacesInterface]=None):  # noqa: E501
        """GetListBaseInterfacesInterface - a model defined in Swagger

        :param openconfig_aclinterface: The openconfig_aclinterface of this GetListBaseInterfacesInterface.  # noqa: E501
        :type openconfig_aclinterface: List[GetAclOpenconfigaclaclInterfacesInterface]
        """
        self.swagger_types = {
            'openconfig_aclinterface': List[GetAclOpenconfigaclaclInterfacesInterface]
        }

        self.attribute_map = {
            'openconfig_aclinterface': 'openconfig-acl:interface'
        }

        self._openconfig_aclinterface = openconfig_aclinterface

    @classmethod
    def from_dict(cls, dikt) -> 'GetListBaseInterfacesInterface':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_list_base_interfaces_interface of this GetListBaseInterfacesInterface.  # noqa: E501
        :rtype: GetListBaseInterfacesInterface
        """
        return util.deserialize_model(dikt, cls)

    @property
    def openconfig_aclinterface(self) -> List[GetAclOpenconfigaclaclInterfacesInterface]:
        """Gets the openconfig_aclinterface of this GetListBaseInterfacesInterface.


        :return: The openconfig_aclinterface of this GetListBaseInterfacesInterface.
        :rtype: List[GetAclOpenconfigaclaclInterfacesInterface]
        """
        return self._openconfig_aclinterface

    @openconfig_aclinterface.setter
    def openconfig_aclinterface(self, openconfig_aclinterface: List[GetAclOpenconfigaclaclInterfacesInterface]):
        """Sets the openconfig_aclinterface of this GetListBaseInterfacesInterface.


        :param openconfig_aclinterface: The openconfig_aclinterface of this GetListBaseInterfacesInterface.
        :type openconfig_aclinterface: List[GetAclOpenconfigaclaclInterfacesInterface]
        """

        self._openconfig_aclinterface = openconfig_aclinterface
