# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_acl_openconfigaclacl_interfaces_ingressaclsets_aclentries_state import GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesState  # noqa: F401,E501
from swagger_server import util


class GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, sequence_id: int=None, state: GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesState=None):  # noqa: E501
        """GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry - a model defined in Swagger

        :param sequence_id: The sequence_id of this GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.  # noqa: E501
        :type sequence_id: int
        :param state: The state of this GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.  # noqa: E501
        :type state: GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesState
        """
        self.swagger_types = {
            'sequence_id': int,
            'state': GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesState
        }

        self.attribute_map = {
            'sequence_id': 'sequence-id',
            'state': 'state'
        }

        self._sequence_id = sequence_id
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_acl_openconfigaclacl_interfaces_ingressaclsets_aclentries_aclentry of this GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.  # noqa: E501
        :rtype: GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sequence_id(self) -> int:
        """Gets the sequence_id of this GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.


        :return: The sequence_id of this GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.
        :rtype: int
        """
        return self._sequence_id

    @sequence_id.setter
    def sequence_id(self, sequence_id: int):
        """Sets the sequence_id of this GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.


        :param sequence_id: The sequence_id of this GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.
        :type sequence_id: int
        """
        if sequence_id is None:
            raise ValueError("Invalid value for `sequence_id`, must not be `None`")  # noqa: E501

        self._sequence_id = sequence_id

    @property
    def state(self) -> GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesState:
        """Gets the state of this GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.


        :return: The state of this GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.
        :rtype: GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesState
        """
        return self._state

    @state.setter
    def state(self, state: GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesState):
        """Sets the state of this GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.


        :param state: The state of this GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.
        :type state: GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesState
        """

        self._state = state
