# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_acl_openconfigaclacl_aclsets_aclentries_ipv6 import GetAclOpenconfigaclaclAclsetsAclentriesIpv6  # noqa: F401,E501
from swagger_server import util


class GetAclEntryIpv6(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, openconfig_aclipv6: GetAclOpenconfigaclaclAclsetsAclentriesIpv6=None):  # noqa: E501
        """GetAclEntryIpv6 - a model defined in Swagger

        :param openconfig_aclipv6: The openconfig_aclipv6 of this GetAclEntryIpv6.  # noqa: E501
        :type openconfig_aclipv6: GetAclOpenconfigaclaclAclsetsAclentriesIpv6
        """
        self.swagger_types = {
            'openconfig_aclipv6': GetAclOpenconfigaclaclAclsetsAclentriesIpv6
        }

        self.attribute_map = {
            'openconfig_aclipv6': 'openconfig-acl:ipv6'
        }

        self._openconfig_aclipv6 = openconfig_aclipv6

    @classmethod
    def from_dict(cls, dikt) -> 'GetAclEntryIpv6':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_acl_entry_ipv6 of this GetAclEntryIpv6.  # noqa: E501
        :rtype: GetAclEntryIpv6
        """
        return util.deserialize_model(dikt, cls)

    @property
    def openconfig_aclipv6(self) -> GetAclOpenconfigaclaclAclsetsAclentriesIpv6:
        """Gets the openconfig_aclipv6 of this GetAclEntryIpv6.


        :return: The openconfig_aclipv6 of this GetAclEntryIpv6.
        :rtype: GetAclOpenconfigaclaclAclsetsAclentriesIpv6
        """
        return self._openconfig_aclipv6

    @openconfig_aclipv6.setter
    def openconfig_aclipv6(self, openconfig_aclipv6: GetAclOpenconfigaclaclAclsetsAclentriesIpv6):
        """Sets the openconfig_aclipv6 of this GetAclEntryIpv6.


        :param openconfig_aclipv6: The openconfig_aclipv6 of this GetAclEntryIpv6.
        :type openconfig_aclipv6: GetAclOpenconfigaclaclAclsetsAclentriesIpv6
        """

        self._openconfig_aclipv6 = openconfig_aclipv6
