# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_acl_openconfigaclacl_interfaces_ingressaclsets_aclentries_aclentry import GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry  # noqa: F401,E501
from swagger_server import util


class GetListBaseEgressAclSetAclEntriesAclEntry(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, openconfig_aclacl_entry: List[GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry]=None):  # noqa: E501
        """GetListBaseEgressAclSetAclEntriesAclEntry - a model defined in Swagger

        :param openconfig_aclacl_entry: The openconfig_aclacl_entry of this GetListBaseEgressAclSetAclEntriesAclEntry.  # noqa: E501
        :type openconfig_aclacl_entry: List[GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry]
        """
        self.swagger_types = {
            'openconfig_aclacl_entry': List[GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry]
        }

        self.attribute_map = {
            'openconfig_aclacl_entry': 'openconfig-acl:acl-entry'
        }

        self._openconfig_aclacl_entry = openconfig_aclacl_entry

    @classmethod
    def from_dict(cls, dikt) -> 'GetListBaseEgressAclSetAclEntriesAclEntry':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_list_base_egress_acl_set_acl_entries_acl_entry of this GetListBaseEgressAclSetAclEntriesAclEntry.  # noqa: E501
        :rtype: GetListBaseEgressAclSetAclEntriesAclEntry
        """
        return util.deserialize_model(dikt, cls)

    @property
    def openconfig_aclacl_entry(self) -> List[GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry]:
        """Gets the openconfig_aclacl_entry of this GetListBaseEgressAclSetAclEntriesAclEntry.


        :return: The openconfig_aclacl_entry of this GetListBaseEgressAclSetAclEntriesAclEntry.
        :rtype: List[GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry]
        """
        return self._openconfig_aclacl_entry

    @openconfig_aclacl_entry.setter
    def openconfig_aclacl_entry(self, openconfig_aclacl_entry: List[GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry]):
        """Sets the openconfig_aclacl_entry of this GetListBaseEgressAclSetAclEntriesAclEntry.


        :param openconfig_aclacl_entry: The openconfig_aclacl_entry of this GetListBaseEgressAclSetAclEntriesAclEntry.
        :type openconfig_aclacl_entry: List[GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry]
        """

        self._openconfig_aclacl_entry = openconfig_aclacl_entry
