# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_acl_acl_sets_acl_set_openconfigaclaclset import GetAclAclSetsAclSetOpenconfigaclaclset  # noqa: F401,E501
from swagger_server import util


class GetAclAclSetsAclSet(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, openconfig_aclacl_set: GetAclAclSetsAclSetOpenconfigaclaclset=None):  # noqa: E501
        """GetAclAclSetsAclSet - a model defined in Swagger

        :param openconfig_aclacl_set: The openconfig_aclacl_set of this GetAclAclSetsAclSet.  # noqa: E501
        :type openconfig_aclacl_set: GetAclAclSetsAclSetOpenconfigaclaclset
        """
        self.swagger_types = {
            'openconfig_aclacl_set': GetAclAclSetsAclSetOpenconfigaclaclset
        }

        self.attribute_map = {
            'openconfig_aclacl_set': 'openconfig-acl:acl-set'
        }

        self._openconfig_aclacl_set = openconfig_aclacl_set

    @classmethod
    def from_dict(cls, dikt) -> 'GetAclAclSetsAclSet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_acl_acl_sets_acl_set of this GetAclAclSetsAclSet.  # noqa: E501
        :rtype: GetAclAclSetsAclSet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def openconfig_aclacl_set(self) -> GetAclAclSetsAclSetOpenconfigaclaclset:
        """Gets the openconfig_aclacl_set of this GetAclAclSetsAclSet.


        :return: The openconfig_aclacl_set of this GetAclAclSetsAclSet.
        :rtype: GetAclAclSetsAclSetOpenconfigaclaclset
        """
        return self._openconfig_aclacl_set

    @openconfig_aclacl_set.setter
    def openconfig_aclacl_set(self, openconfig_aclacl_set: GetAclAclSetsAclSetOpenconfigaclaclset):
        """Sets the openconfig_aclacl_set of this GetAclAclSetsAclSet.


        :param openconfig_aclacl_set: The openconfig_aclacl_set of this GetAclAclSetsAclSet.
        :type openconfig_aclacl_set: GetAclAclSetsAclSetOpenconfigaclaclset
        """

        self._openconfig_aclacl_set = openconfig_aclacl_set
