# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_acl_openconfigaclacl_interfaces_ingressaclsets_aclentries import GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentries  # noqa: F401,E501
from swagger_server import util


class GetIngressAclSetAclEntries(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, openconfig_aclacl_entries: GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentries=None):  # noqa: E501
        """GetIngressAclSetAclEntries - a model defined in Swagger

        :param openconfig_aclacl_entries: The openconfig_aclacl_entries of this GetIngressAclSetAclEntries.  # noqa: E501
        :type openconfig_aclacl_entries: GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentries
        """
        self.swagger_types = {
            'openconfig_aclacl_entries': GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentries
        }

        self.attribute_map = {
            'openconfig_aclacl_entries': 'openconfig-acl:acl-entries'
        }

        self._openconfig_aclacl_entries = openconfig_aclacl_entries

    @classmethod
    def from_dict(cls, dikt) -> 'GetIngressAclSetAclEntries':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_ingress_acl_set_acl_entries of this GetIngressAclSetAclEntries.  # noqa: E501
        :rtype: GetIngressAclSetAclEntries
        """
        return util.deserialize_model(dikt, cls)

    @property
    def openconfig_aclacl_entries(self) -> GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentries:
        """Gets the openconfig_aclacl_entries of this GetIngressAclSetAclEntries.


        :return: The openconfig_aclacl_entries of this GetIngressAclSetAclEntries.
        :rtype: GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentries
        """
        return self._openconfig_aclacl_entries

    @openconfig_aclacl_entries.setter
    def openconfig_aclacl_entries(self, openconfig_aclacl_entries: GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentries):
        """Sets the openconfig_aclacl_entries of this GetIngressAclSetAclEntries.


        :param openconfig_aclacl_entries: The openconfig_aclacl_entries of this GetIngressAclSetAclEntries.
        :type openconfig_aclacl_entries: GetAclOpenconfigaclaclInterfacesIngressaclsetsAclentries
        """

        self._openconfig_aclacl_entries = openconfig_aclacl_entries
