# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.acl_entry_transport import AclEntryTransport  # noqa: F401,E501
from swagger_server.models.acl_openconfigaclacl_aclsets_aclentries_transport import AclOpenconfigaclaclAclsetsAclentriesTransport  # noqa: F401,E501
from swagger_server import util


class PatchAclEntryTransport(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, openconfig_acltransport: AclOpenconfigaclaclAclsetsAclentriesTransport=None):  # noqa: E501
        """PatchAclEntryTransport - a model defined in Swagger

        :param openconfig_acltransport: The openconfig_acltransport of this PatchAclEntryTransport.  # noqa: E501
        :type openconfig_acltransport: AclOpenconfigaclaclAclsetsAclentriesTransport
        """
        self.swagger_types = {
            'openconfig_acltransport': AclOpenconfigaclaclAclsetsAclentriesTransport
        }

        self.attribute_map = {
            'openconfig_acltransport': 'openconfig-acl:transport'
        }

        self._openconfig_acltransport = openconfig_acltransport

    @classmethod
    def from_dict(cls, dikt) -> 'PatchAclEntryTransport':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The patch_acl_entry_transport of this PatchAclEntryTransport.  # noqa: E501
        :rtype: PatchAclEntryTransport
        """
        return util.deserialize_model(dikt, cls)

    @property
    def openconfig_acltransport(self) -> AclOpenconfigaclaclAclsetsAclentriesTransport:
        """Gets the openconfig_acltransport of this PatchAclEntryTransport.


        :return: The openconfig_acltransport of this PatchAclEntryTransport.
        :rtype: AclOpenconfigaclaclAclsetsAclentriesTransport
        """
        return self._openconfig_acltransport

    @openconfig_acltransport.setter
    def openconfig_acltransport(self, openconfig_acltransport: AclOpenconfigaclaclAclsetsAclentriesTransport):
        """Sets the openconfig_acltransport of this PatchAclEntryTransport.


        :param openconfig_acltransport: The openconfig_acltransport of this PatchAclEntryTransport.
        :type openconfig_acltransport: AclOpenconfigaclaclAclsetsAclentriesTransport
        """

        self._openconfig_acltransport = openconfig_acltransport
