# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.acl_openconfigaclacl_interfaces_ingressaclsets_config import AclOpenconfigaclaclInterfacesIngressaclsetsConfig  # noqa: F401,E501
from swagger_server.models.ingress_acl_set_config import IngressAclSetConfig  # noqa: F401,E501
from swagger_server import util


class PatchIngressAclSetConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, openconfig_aclconfig: AclOpenconfigaclaclInterfacesIngressaclsetsConfig=None):  # noqa: E501
        """PatchIngressAclSetConfig - a model defined in Swagger

        :param openconfig_aclconfig: The openconfig_aclconfig of this PatchIngressAclSetConfig.  # noqa: E501
        :type openconfig_aclconfig: AclOpenconfigaclaclInterfacesIngressaclsetsConfig
        """
        self.swagger_types = {
            'openconfig_aclconfig': AclOpenconfigaclaclInterfacesIngressaclsetsConfig
        }

        self.attribute_map = {
            'openconfig_aclconfig': 'openconfig-acl:config'
        }

        self._openconfig_aclconfig = openconfig_aclconfig

    @classmethod
    def from_dict(cls, dikt) -> 'PatchIngressAclSetConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The patch_ingress_acl_set_config of this PatchIngressAclSetConfig.  # noqa: E501
        :rtype: PatchIngressAclSetConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def openconfig_aclconfig(self) -> AclOpenconfigaclaclInterfacesIngressaclsetsConfig:
        """Gets the openconfig_aclconfig of this PatchIngressAclSetConfig.


        :return: The openconfig_aclconfig of this PatchIngressAclSetConfig.
        :rtype: AclOpenconfigaclaclInterfacesIngressaclsetsConfig
        """
        return self._openconfig_aclconfig

    @openconfig_aclconfig.setter
    def openconfig_aclconfig(self, openconfig_aclconfig: AclOpenconfigaclaclInterfacesIngressaclsetsConfig):
        """Sets the openconfig_aclconfig of this PatchIngressAclSetConfig.


        :param openconfig_aclconfig: The openconfig_aclconfig of this PatchIngressAclSetConfig.
        :type openconfig_aclconfig: AclOpenconfigaclaclInterfacesIngressaclsetsConfig
        """

        self._openconfig_aclconfig = openconfig_aclconfig
