# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.interface_egress_acl_sets_egress_acl_set import InterfaceEgressAclSetsEgressAclSet  # noqa: F401,E501
from swagger_server.models.interface_ingress_acl_sets_ingress_acl_set_openconfigaclingressaclset import InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset  # noqa: F401,E501
from swagger_server import util


class PatchInterfaceEgressAclSetsEgressAclSet(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, openconfig_aclegress_acl_set: InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset=None):  # noqa: E501
        """PatchInterfaceEgressAclSetsEgressAclSet - a model defined in Swagger

        :param openconfig_aclegress_acl_set: The openconfig_aclegress_acl_set of this PatchInterfaceEgressAclSetsEgressAclSet.  # noqa: E501
        :type openconfig_aclegress_acl_set: InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset
        """
        self.swagger_types = {
            'openconfig_aclegress_acl_set': InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset
        }

        self.attribute_map = {
            'openconfig_aclegress_acl_set': 'openconfig-acl:egress-acl-set'
        }

        self._openconfig_aclegress_acl_set = openconfig_aclegress_acl_set

    @classmethod
    def from_dict(cls, dikt) -> 'PatchInterfaceEgressAclSetsEgressAclSet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The patch_interface_egress_acl_sets_egress_acl_set of this PatchInterfaceEgressAclSetsEgressAclSet.  # noqa: E501
        :rtype: PatchInterfaceEgressAclSetsEgressAclSet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def openconfig_aclegress_acl_set(self) -> InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset:
        """Gets the openconfig_aclegress_acl_set of this PatchInterfaceEgressAclSetsEgressAclSet.


        :return: The openconfig_aclegress_acl_set of this PatchInterfaceEgressAclSetsEgressAclSet.
        :rtype: InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset
        """
        return self._openconfig_aclegress_acl_set

    @openconfig_aclegress_acl_set.setter
    def openconfig_aclegress_acl_set(self, openconfig_aclegress_acl_set: InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset):
        """Sets the openconfig_aclegress_acl_set of this PatchInterfaceEgressAclSetsEgressAclSet.


        :param openconfig_aclegress_acl_set: The openconfig_aclegress_acl_set of this PatchInterfaceEgressAclSetsEgressAclSet.
        :type openconfig_aclegress_acl_set: InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset
        """

        self._openconfig_aclegress_acl_set = openconfig_aclegress_acl_set
