# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.interface_ingress_acl_sets_ingress_acl_set import InterfaceIngressAclSetsIngressAclSet  # noqa: F401,E501
from swagger_server.models.interface_ingress_acl_sets_ingress_acl_set_openconfigaclingressaclset import InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset  # noqa: F401,E501
from swagger_server import util


class PatchInterfaceIngressAclSetsIngressAclSet(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, openconfig_aclingress_acl_set: InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset=None):  # noqa: E501
        """PatchInterfaceIngressAclSetsIngressAclSet - a model defined in Swagger

        :param openconfig_aclingress_acl_set: The openconfig_aclingress_acl_set of this PatchInterfaceIngressAclSetsIngressAclSet.  # noqa: E501
        :type openconfig_aclingress_acl_set: InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset
        """
        self.swagger_types = {
            'openconfig_aclingress_acl_set': InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset
        }

        self.attribute_map = {
            'openconfig_aclingress_acl_set': 'openconfig-acl:ingress-acl-set'
        }

        self._openconfig_aclingress_acl_set = openconfig_aclingress_acl_set

    @classmethod
    def from_dict(cls, dikt) -> 'PatchInterfaceIngressAclSetsIngressAclSet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The patch_interface_ingress_acl_sets_ingress_acl_set of this PatchInterfaceIngressAclSetsIngressAclSet.  # noqa: E501
        :rtype: PatchInterfaceIngressAclSetsIngressAclSet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def openconfig_aclingress_acl_set(self) -> InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset:
        """Gets the openconfig_aclingress_acl_set of this PatchInterfaceIngressAclSetsIngressAclSet.


        :return: The openconfig_aclingress_acl_set of this PatchInterfaceIngressAclSetsIngressAclSet.
        :rtype: InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset
        """
        return self._openconfig_aclingress_acl_set

    @openconfig_aclingress_acl_set.setter
    def openconfig_aclingress_acl_set(self, openconfig_aclingress_acl_set: InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset):
        """Sets the openconfig_aclingress_acl_set of this PatchInterfaceIngressAclSetsIngressAclSet.


        :param openconfig_aclingress_acl_set: The openconfig_aclingress_acl_set of this PatchInterfaceIngressAclSetsIngressAclSet.
        :type openconfig_aclingress_acl_set: InterfaceIngressAclSetsIngressAclSetOpenconfigaclingressaclset
        """

        self._openconfig_aclingress_acl_set = openconfig_aclingress_acl_set
