# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.acl_openconfigaclacl_aclsets_aclentries_actions_config import AclOpenconfigaclaclAclsetsAclentriesActionsConfig  # noqa: F401,E501
from swagger_server.models.actions_config import ActionsConfig  # noqa: F401,E501
from swagger_server import util


class PutActionsConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, openconfig_aclconfig: AclOpenconfigaclaclAclsetsAclentriesActionsConfig=None):  # noqa: E501
        """PutActionsConfig - a model defined in Swagger

        :param openconfig_aclconfig: The openconfig_aclconfig of this PutActionsConfig.  # noqa: E501
        :type openconfig_aclconfig: AclOpenconfigaclaclAclsetsAclentriesActionsConfig
        """
        self.swagger_types = {
            'openconfig_aclconfig': AclOpenconfigaclaclAclsetsAclentriesActionsConfig
        }

        self.attribute_map = {
            'openconfig_aclconfig': 'openconfig-acl:config'
        }

        self._openconfig_aclconfig = openconfig_aclconfig

    @classmethod
    def from_dict(cls, dikt) -> 'PutActionsConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The put_actions_config of this PutActionsConfig.  # noqa: E501
        :rtype: PutActionsConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def openconfig_aclconfig(self) -> AclOpenconfigaclaclAclsetsAclentriesActionsConfig:
        """Gets the openconfig_aclconfig of this PutActionsConfig.


        :return: The openconfig_aclconfig of this PutActionsConfig.
        :rtype: AclOpenconfigaclaclAclsetsAclentriesActionsConfig
        """
        return self._openconfig_aclconfig

    @openconfig_aclconfig.setter
    def openconfig_aclconfig(self, openconfig_aclconfig: AclOpenconfigaclaclAclsetsAclentriesActionsConfig):
        """Sets the openconfig_aclconfig of this PutActionsConfig.


        :param openconfig_aclconfig: The openconfig_aclconfig of this PutActionsConfig.
        :type openconfig_aclconfig: AclOpenconfigaclaclAclsetsAclentriesActionsConfig
        """

        self._openconfig_aclconfig = openconfig_aclconfig
