# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.config_source_flow_label import ConfigSourceFlowLabel  # noqa: F401,E501
from swagger_server import util


class PutConfigSourceFlowLabel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, source_flow_label: int=None):  # noqa: E501
        """PutConfigSourceFlowLabel - a model defined in Swagger

        :param source_flow_label: The source_flow_label of this PutConfigSourceFlowLabel.  # noqa: E501
        :type source_flow_label: int
        """
        self.swagger_types = {
            'source_flow_label': int
        }

        self.attribute_map = {
            'source_flow_label': 'source-flow-label'
        }

        self._source_flow_label = source_flow_label

    @classmethod
    def from_dict(cls, dikt) -> 'PutConfigSourceFlowLabel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The put_config_source_flow_label of this PutConfigSourceFlowLabel.  # noqa: E501
        :rtype: PutConfigSourceFlowLabel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source_flow_label(self) -> int:
        """Gets the source_flow_label of this PutConfigSourceFlowLabel.


        :return: The source_flow_label of this PutConfigSourceFlowLabel.
        :rtype: int
        """
        return self._source_flow_label

    @source_flow_label.setter
    def source_flow_label(self, source_flow_label: int):
        """Sets the source_flow_label of this PutConfigSourceFlowLabel.


        :param source_flow_label: The source_flow_label of this PutConfigSourceFlowLabel.
        :type source_flow_label: int
        """

        self._source_flow_label = source_flow_label
