# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.acl_openconfigaclacl_aclsets_aclentries_transport_config import AclOpenconfigaclaclAclsetsAclentriesTransportConfig  # noqa: F401,E501
from swagger_server import util


class TransportConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, openconfig_aclconfig: AclOpenconfigaclaclAclsetsAclentriesTransportConfig=None):  # noqa: E501
        """TransportConfig - a model defined in Swagger

        :param openconfig_aclconfig: The openconfig_aclconfig of this TransportConfig.  # noqa: E501
        :type openconfig_aclconfig: AclOpenconfigaclaclAclsetsAclentriesTransportConfig
        """
        self.swagger_types = {
            'openconfig_aclconfig': AclOpenconfigaclaclAclsetsAclentriesTransportConfig
        }

        self.attribute_map = {
            'openconfig_aclconfig': 'openconfig-acl:config'
        }

        self._openconfig_aclconfig = openconfig_aclconfig

    @classmethod
    def from_dict(cls, dikt) -> 'TransportConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transport_config of this TransportConfig.  # noqa: E501
        :rtype: TransportConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def openconfig_aclconfig(self) -> AclOpenconfigaclaclAclsetsAclentriesTransportConfig:
        """Gets the openconfig_aclconfig of this TransportConfig.


        :return: The openconfig_aclconfig of this TransportConfig.
        :rtype: AclOpenconfigaclaclAclsetsAclentriesTransportConfig
        """
        return self._openconfig_aclconfig

    @openconfig_aclconfig.setter
    def openconfig_aclconfig(self, openconfig_aclconfig: AclOpenconfigaclaclAclsetsAclentriesTransportConfig):
        """Sets the openconfig_aclconfig of this TransportConfig.


        :param openconfig_aclconfig: The openconfig_aclconfig of this TransportConfig.
        :type openconfig_aclconfig: AclOpenconfigaclaclAclsetsAclentriesTransportConfig
        """

        self._openconfig_aclconfig = openconfig_aclconfig
