# coding: utf-8

"""
    Sonic NMS

    Network management Open APIs for Broadcom's Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: mohammed.faraaz@broadcom.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.acl_openconfigaclacl_aclsets_aclentries import AclOpenconfigaclaclAclsetsAclentries  # noqa: F401,E501
from swagger_client.models.acl_openconfigaclacl_aclsets_config import AclOpenconfigaclaclAclsetsConfig  # noqa: F401,E501


class AclOpenconfigaclaclAclsetsAclset(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'str',
        'config': 'AclOpenconfigaclaclAclsetsConfig',
        'acl_entries': 'AclOpenconfigaclaclAclsetsAclentries'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'config': 'config',
        'acl_entries': 'acl-entries'
    }

    def __init__(self, name=None, type=None, config=None, acl_entries=None):  # noqa: E501
        """AclOpenconfigaclaclAclsetsAclset - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._type = None
        self._config = None
        self._acl_entries = None
        self.discriminator = None

        self.name = name
        self.type = type
        if config is not None:
            self.config = config
        if acl_entries is not None:
            self.acl_entries = acl_entries

    @property
    def name(self):
        """Gets the name of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501


        :return: The name of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AclOpenconfigaclaclAclsetsAclset.


        :param name: The name of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self):
        """Gets the type of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501


        :return: The type of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AclOpenconfigaclaclAclsetsAclset.


        :param type: The type of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def config(self):
        """Gets the config of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501


        :return: The config of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501
        :rtype: AclOpenconfigaclaclAclsetsConfig
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this AclOpenconfigaclaclAclsetsAclset.


        :param config: The config of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501
        :type: AclOpenconfigaclaclAclsetsConfig
        """

        self._config = config

    @property
    def acl_entries(self):
        """Gets the acl_entries of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501


        :return: The acl_entries of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501
        :rtype: AclOpenconfigaclaclAclsetsAclentries
        """
        return self._acl_entries

    @acl_entries.setter
    def acl_entries(self, acl_entries):
        """Sets the acl_entries of this AclOpenconfigaclaclAclsetsAclset.


        :param acl_entries: The acl_entries of this AclOpenconfigaclaclAclsetsAclset.  # noqa: E501
        :type: AclOpenconfigaclaclAclsetsAclentries
        """

        self._acl_entries = acl_entries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AclOpenconfigaclaclAclsetsAclset, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AclOpenconfigaclaclAclsetsAclset):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
