# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from sonic_acl_client.models.sonic_acl_sonic_acl_sonicaclsonicacl_acltableacltablelist import SonicAclSonicAclSonicaclsonicaclACLTABLEACLTABLELIST  # noqa: F401,E501


class SonicAclSonicAclSonicaclsonicaclACLTABLE(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'acl_table_list': 'list[SonicAclSonicAclSonicaclsonicaclACLTABLEACLTABLELIST]'
    }

    attribute_map = {
        'acl_table_list': 'ACL_TABLE_LIST'
    }

    def __init__(self, acl_table_list=None):  # noqa: E501
        """SonicAclSonicAclSonicaclsonicaclACLTABLE - a model defined in Swagger"""  # noqa: E501

        self._acl_table_list = None
        self.discriminator = None

        if acl_table_list is not None:
            self.acl_table_list = acl_table_list

    @property
    def acl_table_list(self):
        """Gets the acl_table_list of this SonicAclSonicAclSonicaclsonicaclACLTABLE.  # noqa: E501


        :return: The acl_table_list of this SonicAclSonicAclSonicaclsonicaclACLTABLE.  # noqa: E501
        :rtype: list[SonicAclSonicAclSonicaclsonicaclACLTABLEACLTABLELIST]
        """
        return self._acl_table_list

    @acl_table_list.setter
    def acl_table_list(self, acl_table_list):
        """Sets the acl_table_list of this SonicAclSonicAclSonicaclsonicaclACLTABLE.


        :param acl_table_list: The acl_table_list of this SonicAclSonicAclSonicaclsonicaclACLTABLE.  # noqa: E501
        :type: list[SonicAclSonicAclSonicaclsonicaclACLTABLEACLTABLELIST]
        """

        self._acl_table_list = acl_table_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SonicAclSonicAclSonicaclsonicaclACLTABLE, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SonicAclSonicAclSonicaclsonicaclACLTABLE):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
