#!/bin/sh
# Launch the "preferred" shell based on the groups that the user belongs to.
# The preferred shell is either:
#    /bin/bash:          If the user belongs to group "admin"
#    /usr/bin/sonic-cli: Otherwise

if /usr/bin/id -Gn | /bin/grep -qw "admin"; then
    exec /bin/bash $@
else
    exec /usr/bin/sonic-cli
fi
