# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openconfig_acl_client.models.get_openconfig_acl_acl_openconfigaclacl_interfaces_ingressaclsets_aclentries import GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentries  # noqa: F401,E501
from openconfig_acl_client.models.openconfig_acl_acl_openconfigaclacl_interfaces_ingressaclsets_config import OpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsConfig  # noqa: F401,E501


class GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'set_name': 'str',
        'type': 'str',
        'config': 'OpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsConfig',
        'state': 'OpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsConfig',
        'acl_entries': 'GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentries'
    }

    attribute_map = {
        'set_name': 'set-name',
        'type': 'type',
        'config': 'config',
        'state': 'state',
        'acl_entries': 'acl-entries'
    }

    def __init__(self, set_name=None, type=None, config=None, state=None, acl_entries=None):  # noqa: E501
        """GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset - a model defined in Swagger"""  # noqa: E501

        self._set_name = None
        self._type = None
        self._config = None
        self._state = None
        self._acl_entries = None
        self.discriminator = None

        self.set_name = set_name
        self.type = type
        if config is not None:
            self.config = config
        if state is not None:
            self.state = state
        if acl_entries is not None:
            self.acl_entries = acl_entries

    @property
    def set_name(self):
        """Gets the set_name of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501


        :return: The set_name of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501
        :rtype: str
        """
        return self._set_name

    @set_name.setter
    def set_name(self, set_name):
        """Sets the set_name of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.


        :param set_name: The set_name of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501
        :type: str
        """
        if set_name is None:
            raise ValueError("Invalid value for `set_name`, must not be `None`")  # noqa: E501

        self._set_name = set_name

    @property
    def type(self):
        """Gets the type of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501


        :return: The type of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.


        :param type: The type of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def config(self):
        """Gets the config of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501


        :return: The config of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501
        :rtype: OpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsConfig
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.


        :param config: The config of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501
        :type: OpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsConfig
        """

        self._config = config

    @property
    def state(self):
        """Gets the state of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501


        :return: The state of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501
        :rtype: OpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsConfig
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.


        :param state: The state of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501
        :type: OpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsConfig
        """

        self._state = state

    @property
    def acl_entries(self):
        """Gets the acl_entries of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501


        :return: The acl_entries of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501
        :rtype: GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentries
        """
        return self._acl_entries

    @acl_entries.setter
    def acl_entries(self, acl_entries):
        """Sets the acl_entries of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.


        :param acl_entries: The acl_entries of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset.  # noqa: E501
        :type: GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentries
        """

        self._acl_entries = acl_entries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsIngressaclset):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
