# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openconfig_acl_client.models.get_openconfig_acl_acl_openconfigaclacl_interfaces_ingressaclsets_aclentries_state import GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesState  # noqa: F401,E501


class GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sequence_id': 'int',
        'state': 'GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesState'
    }

    attribute_map = {
        'sequence_id': 'sequence-id',
        'state': 'state'
    }

    def __init__(self, sequence_id=None, state=None):  # noqa: E501
        """GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry - a model defined in Swagger"""  # noqa: E501

        self._sequence_id = None
        self._state = None
        self.discriminator = None

        self.sequence_id = sequence_id
        if state is not None:
            self.state = state

    @property
    def sequence_id(self):
        """Gets the sequence_id of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.  # noqa: E501


        :return: The sequence_id of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.  # noqa: E501
        :rtype: int
        """
        return self._sequence_id

    @sequence_id.setter
    def sequence_id(self, sequence_id):
        """Sets the sequence_id of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.


        :param sequence_id: The sequence_id of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.  # noqa: E501
        :type: int
        """
        if sequence_id is None:
            raise ValueError("Invalid value for `sequence_id`, must not be `None`")  # noqa: E501

        self._sequence_id = sequence_id

    @property
    def state(self):
        """Gets the state of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.  # noqa: E501


        :return: The state of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.  # noqa: E501
        :rtype: GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.


        :param state: The state of this GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry.  # noqa: E501
        :type: GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesState
        """

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetOpenconfigAclAclOpenconfigaclaclInterfacesIngressaclsetsAclentriesAclentry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
