# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetOpenconfigAclAclOpenconfigaclaclState(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'counter_capability': 'str'
    }

    attribute_map = {
        'counter_capability': 'counter-capability'
    }

    def __init__(self, counter_capability=None):  # noqa: E501
        """GetOpenconfigAclAclOpenconfigaclaclState - a model defined in Swagger"""  # noqa: E501

        self._counter_capability = None
        self.discriminator = None

        if counter_capability is not None:
            self.counter_capability = counter_capability

    @property
    def counter_capability(self):
        """Gets the counter_capability of this GetOpenconfigAclAclOpenconfigaclaclState.  # noqa: E501


        :return: The counter_capability of this GetOpenconfigAclAclOpenconfigaclaclState.  # noqa: E501
        :rtype: str
        """
        return self._counter_capability

    @counter_capability.setter
    def counter_capability(self, counter_capability):
        """Sets the counter_capability of this GetOpenconfigAclAclOpenconfigaclaclState.


        :param counter_capability: The counter_capability of this GetOpenconfigAclAclOpenconfigaclaclState.  # noqa: E501
        :type: str
        """

        self._counter_capability = counter_capability

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetOpenconfigAclAclOpenconfigaclaclState, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetOpenconfigAclAclOpenconfigaclaclState):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
