FROM {{ docker_nat_load_image }}

ARG docker_container_name
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

RUN echo

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

## Install redis-tools dependencies
## TODO: implicitly install dependencies
RUN apt-get update \
 && apt-get install -f -y libdbus-1-3 libdaemon0 libjansson4 libpython2.7 \
 && apt-get -y install libjemalloc1 \
 && apt-get -y install conntrack

RUN apt-get install -f -y libatomic1 liblua5.1-0 lua-bitop lua-cjson

COPY \
{% for deb in docker_nat_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor -%}
debs/

RUN dpkg -i \
{% for deb in docker_nat_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor %}

COPY ["files/supervisor-proc-exit-listener", "start.sh", "/usr/bin/"]
COPY ["critical_processes", "/etc/supervisor/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["restore_nat_entries.py", "/usr/bin/"]

RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y
RUN rm -rf /debs

ENTRYPOINT ["/usr/bin/supervisord"]

