TARGET = pddf_psu_driver_module

#$(info  ===========$(M)=========)

obj-m := $(TARGET).o 

$(TARGET)-objs := pddf_psu_api.o pddf_psu_driver.o 

ccflags-y := -I$(M)/modules/include
#ccflags-y += -I$(M)/modules/psu
