# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openconfig_spanning_tree_client.models.get_openconfig_spanning_tree_stp_openconfigspanningtreestp_mstp_mstinstances import GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstpMstinstances  # noqa: F401,E501
from openconfig_spanning_tree_client.models.openconfig_spanning_tree_stp_openconfigspanningtreestp_mstp_config import OpenconfigSpanningTreeStpOpenconfigspanningtreestpMstpConfig  # noqa: F401,E501


class GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'config': 'OpenconfigSpanningTreeStpOpenconfigspanningtreestpMstpConfig',
        'state': 'OpenconfigSpanningTreeStpOpenconfigspanningtreestpMstpConfig',
        'mst_instances': 'GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstpMstinstances'
    }

    attribute_map = {
        'config': 'config',
        'state': 'state',
        'mst_instances': 'mst-instances'
    }

    def __init__(self, config=None, state=None, mst_instances=None):  # noqa: E501
        """GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp - a model defined in Swagger"""  # noqa: E501

        self._config = None
        self._state = None
        self._mst_instances = None
        self.discriminator = None

        if config is not None:
            self.config = config
        if state is not None:
            self.state = state
        if mst_instances is not None:
            self.mst_instances = mst_instances

    @property
    def config(self):
        """Gets the config of this GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp.  # noqa: E501


        :return: The config of this GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp.  # noqa: E501
        :rtype: OpenconfigSpanningTreeStpOpenconfigspanningtreestpMstpConfig
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp.


        :param config: The config of this GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp.  # noqa: E501
        :type: OpenconfigSpanningTreeStpOpenconfigspanningtreestpMstpConfig
        """

        self._config = config

    @property
    def state(self):
        """Gets the state of this GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp.  # noqa: E501


        :return: The state of this GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp.  # noqa: E501
        :rtype: OpenconfigSpanningTreeStpOpenconfigspanningtreestpMstpConfig
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp.


        :param state: The state of this GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp.  # noqa: E501
        :type: OpenconfigSpanningTreeStpOpenconfigspanningtreestpMstpConfig
        """

        self._state = state

    @property
    def mst_instances(self):
        """Gets the mst_instances of this GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp.  # noqa: E501


        :return: The mst_instances of this GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp.  # noqa: E501
        :rtype: GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstpMstinstances
        """
        return self._mst_instances

    @mst_instances.setter
    def mst_instances(self, mst_instances):
        """Sets the mst_instances of this GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp.


        :param mst_instances: The mst_instances of this GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp.  # noqa: E501
        :type: GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstpMstinstances
        """

        self._mst_instances = mst_instances

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetOpenconfigSpanningTreeStpOpenconfigspanningtreestpMstp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
