# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openconfig_spanning_tree_client.models.openconfig_spanning_tree_stp_interfaces_interface_config_link_type import OpenconfigSpanningTreeStpInterfacesInterfaceConfigLinkType  # noqa: F401,E501


class PatchOpenconfigSpanningTreeStpInterfacesInterfaceConfigLinkType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'openconfig_spanning_treelink_type': 'str'
    }

    attribute_map = {
        'openconfig_spanning_treelink_type': 'openconfig-spanning-tree:link-type'
    }

    def __init__(self, openconfig_spanning_treelink_type=None):  # noqa: E501
        """PatchOpenconfigSpanningTreeStpInterfacesInterfaceConfigLinkType - a model defined in Swagger"""  # noqa: E501

        self._openconfig_spanning_treelink_type = None
        self.discriminator = None

        if openconfig_spanning_treelink_type is not None:
            self.openconfig_spanning_treelink_type = openconfig_spanning_treelink_type

    @property
    def openconfig_spanning_treelink_type(self):
        """Gets the openconfig_spanning_treelink_type of this PatchOpenconfigSpanningTreeStpInterfacesInterfaceConfigLinkType.  # noqa: E501


        :return: The openconfig_spanning_treelink_type of this PatchOpenconfigSpanningTreeStpInterfacesInterfaceConfigLinkType.  # noqa: E501
        :rtype: str
        """
        return self._openconfig_spanning_treelink_type

    @openconfig_spanning_treelink_type.setter
    def openconfig_spanning_treelink_type(self, openconfig_spanning_treelink_type):
        """Sets the openconfig_spanning_treelink_type of this PatchOpenconfigSpanningTreeStpInterfacesInterfaceConfigLinkType.


        :param openconfig_spanning_treelink_type: The openconfig_spanning_treelink_type of this PatchOpenconfigSpanningTreeStpInterfacesInterfaceConfigLinkType.  # noqa: E501
        :type: str
        """
        allowed_values = ["P2P", "SHARED"]  # noqa: E501
        if openconfig_spanning_treelink_type not in allowed_values:
            raise ValueError(
                "Invalid value for `openconfig_spanning_treelink_type` ({0}), must be one of {1}"  # noqa: E501
                .format(openconfig_spanning_treelink_type, allowed_values)
            )

        self._openconfig_spanning_treelink_type = openconfig_spanning_treelink_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PatchOpenconfigSpanningTreeStpInterfacesInterfaceConfigLinkType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PatchOpenconfigSpanningTreeStpInterfacesInterfaceConfigLinkType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
