# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openconfig_system_client.models.openconfig_system_system_openconfigsystemsystem_logging_console_selectors_config import OpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsConfig  # noqa: F401,E501


class GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'facility': 'str',
        'severity': 'str',
        'config': 'OpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsConfig',
        'state': 'OpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsConfig'
    }

    attribute_map = {
        'facility': 'facility',
        'severity': 'severity',
        'config': 'config',
        'state': 'state'
    }

    def __init__(self, facility=None, severity=None, config=None, state=None):  # noqa: E501
        """GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector - a model defined in Swagger"""  # noqa: E501

        self._facility = None
        self._severity = None
        self._config = None
        self._state = None
        self.discriminator = None

        self.facility = facility
        self.severity = severity
        if config is not None:
            self.config = config
        if state is not None:
            self.state = state

    @property
    def facility(self):
        """Gets the facility of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.  # noqa: E501


        :return: The facility of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.  # noqa: E501
        :rtype: str
        """
        return self._facility

    @facility.setter
    def facility(self, facility):
        """Sets the facility of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.


        :param facility: The facility of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.  # noqa: E501
        :type: str
        """
        if facility is None:
            raise ValueError("Invalid value for `facility`, must not be `None`")  # noqa: E501

        self._facility = facility

    @property
    def severity(self):
        """Gets the severity of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.  # noqa: E501


        :return: The severity of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.  # noqa: E501
        :rtype: str
        """
        return self._severity

    @severity.setter
    def severity(self, severity):
        """Sets the severity of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.


        :param severity: The severity of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.  # noqa: E501
        :type: str
        """
        if severity is None:
            raise ValueError("Invalid value for `severity`, must not be `None`")  # noqa: E501
        allowed_values = ["EMERGENCY", "ALERT", "CRITICAL", "ERROR", "WARNING", "NOTICE", "INFORMATIONAL", "DEBUG"]  # noqa: E501
        if severity not in allowed_values:
            raise ValueError(
                "Invalid value for `severity` ({0}), must be one of {1}"  # noqa: E501
                .format(severity, allowed_values)
            )

        self._severity = severity

    @property
    def config(self):
        """Gets the config of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.  # noqa: E501


        :return: The config of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.  # noqa: E501
        :rtype: OpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsConfig
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.


        :param config: The config of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.  # noqa: E501
        :type: OpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsConfig
        """

        self._config = config

    @property
    def state(self):
        """Gets the state of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.  # noqa: E501


        :return: The state of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.  # noqa: E501
        :rtype: OpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsConfig
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.


        :param state: The state of this GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector.  # noqa: E501
        :type: OpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsConfig
        """

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetOpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectorsSelector):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
