# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openconfig_system_client.models.openconfig_system_system_openconfigsystemsystem_logging_console_selectors import OpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectors  # noqa: F401,E501
from openconfig_system_client.models.openconfig_system_system_openconfigsystemsystem_logging_remoteservers_config import OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversConfig  # noqa: F401,E501


class OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'host': 'str',
        'config': 'OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversConfig',
        'selectors': 'OpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectors'
    }

    attribute_map = {
        'host': 'host',
        'config': 'config',
        'selectors': 'selectors'
    }

    def __init__(self, host=None, config=None, selectors=None):  # noqa: E501
        """OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver - a model defined in Swagger"""  # noqa: E501

        self._host = None
        self._config = None
        self._selectors = None
        self.discriminator = None

        self.host = host
        if config is not None:
            self.config = config
        if selectors is not None:
            self.selectors = selectors

    @property
    def host(self):
        """Gets the host of this OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver.  # noqa: E501


        :return: The host of this OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver.  # noqa: E501
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host):
        """Sets the host of this OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver.


        :param host: The host of this OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver.  # noqa: E501
        :type: str
        """
        if host is None:
            raise ValueError("Invalid value for `host`, must not be `None`")  # noqa: E501

        self._host = host

    @property
    def config(self):
        """Gets the config of this OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver.  # noqa: E501


        :return: The config of this OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver.  # noqa: E501
        :rtype: OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversConfig
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver.


        :param config: The config of this OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver.  # noqa: E501
        :type: OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversConfig
        """

        self._config = config

    @property
    def selectors(self):
        """Gets the selectors of this OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver.  # noqa: E501


        :return: The selectors of this OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver.  # noqa: E501
        :rtype: OpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectors
        """
        return self._selectors

    @selectors.setter
    def selectors(self, selectors):
        """Sets the selectors of this OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver.


        :param selectors: The selectors of this OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver.  # noqa: E501
        :type: OpenconfigSystemSystemOpenconfigsystemsystemLoggingConsoleSelectors
        """

        self._selectors = selectors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OpenconfigSystemSystemOpenconfigsystemsystemLoggingRemoteserversRemoteserver):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
