# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openconfig_system_client.models.openconfig_system_system_aaa_accounting_config import OpenconfigSystemSystemAaaAccountingConfig  # noqa: F401,E501
from openconfig_system_client.models.openconfig_system_system_aaa_accounting_events import OpenconfigSystemSystemAaaAccountingEvents  # noqa: F401,E501
from openconfig_system_client.models.openconfig_system_system_openconfigsystemsystem_aaa_accounting_config import OpenconfigSystemSystemOpenconfigsystemsystemAaaAccountingConfig  # noqa: F401,E501
from openconfig_system_client.models.openconfig_system_system_openconfigsystemsystem_aaa_accounting_events import OpenconfigSystemSystemOpenconfigsystemsystemAaaAccountingEvents  # noqa: F401,E501


class PostOpenconfigSystemSystemAaaAccountingConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'openconfig_systemconfig': 'OpenconfigSystemSystemOpenconfigsystemsystemAaaAccountingConfig',
        'openconfig_systemevents': 'OpenconfigSystemSystemOpenconfigsystemsystemAaaAccountingEvents'
    }

    attribute_map = {
        'openconfig_systemconfig': 'openconfig-system:config',
        'openconfig_systemevents': 'openconfig-system:events'
    }

    def __init__(self, openconfig_systemconfig=None, openconfig_systemevents=None):  # noqa: E501
        """PostOpenconfigSystemSystemAaaAccountingConfig - a model defined in Swagger"""  # noqa: E501

        self._openconfig_systemconfig = None
        self._openconfig_systemevents = None
        self.discriminator = None

        if openconfig_systemconfig is not None:
            self.openconfig_systemconfig = openconfig_systemconfig
        if openconfig_systemevents is not None:
            self.openconfig_systemevents = openconfig_systemevents

    @property
    def openconfig_systemconfig(self):
        """Gets the openconfig_systemconfig of this PostOpenconfigSystemSystemAaaAccountingConfig.  # noqa: E501


        :return: The openconfig_systemconfig of this PostOpenconfigSystemSystemAaaAccountingConfig.  # noqa: E501
        :rtype: OpenconfigSystemSystemOpenconfigsystemsystemAaaAccountingConfig
        """
        return self._openconfig_systemconfig

    @openconfig_systemconfig.setter
    def openconfig_systemconfig(self, openconfig_systemconfig):
        """Sets the openconfig_systemconfig of this PostOpenconfigSystemSystemAaaAccountingConfig.


        :param openconfig_systemconfig: The openconfig_systemconfig of this PostOpenconfigSystemSystemAaaAccountingConfig.  # noqa: E501
        :type: OpenconfigSystemSystemOpenconfigsystemsystemAaaAccountingConfig
        """

        self._openconfig_systemconfig = openconfig_systemconfig

    @property
    def openconfig_systemevents(self):
        """Gets the openconfig_systemevents of this PostOpenconfigSystemSystemAaaAccountingConfig.  # noqa: E501


        :return: The openconfig_systemevents of this PostOpenconfigSystemSystemAaaAccountingConfig.  # noqa: E501
        :rtype: OpenconfigSystemSystemOpenconfigsystemsystemAaaAccountingEvents
        """
        return self._openconfig_systemevents

    @openconfig_systemevents.setter
    def openconfig_systemevents(self, openconfig_systemevents):
        """Sets the openconfig_systemevents of this PostOpenconfigSystemSystemAaaAccountingConfig.


        :param openconfig_systemevents: The openconfig_systemevents of this PostOpenconfigSystemSystemAaaAccountingConfig.  # noqa: E501
        :type: OpenconfigSystemSystemOpenconfigsystemsystemAaaAccountingEvents
        """

        self._openconfig_systemevents = openconfig_systemevents

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostOpenconfigSystemSystemAaaAccountingConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostOpenconfigSystemSystemAaaAccountingConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
