ARG slave_tag_ref=latest
ARG slave_image

# Add user
ARG user
ARG uid
ARG guid
ARG hostname
ARG email=$user@contoso.com

FROM ${slave_image}:${slave_tag_ref}

RUN sudo chmod 0666 /etc/default/docker
RUN sudo echo DOCKER_OPTS=\"--experimental --storage-driver=vfs\" >> /etc/default/docker
RUN sudo chmod 0644 /etc/default/docker
