# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetOpenconfigTelemetryTelemetrySystemSubscriptionsPersistentSubscriptionsPersistentSubscriptionSensorProfilesSensorProfileConfigSuppressRedundant(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'openconfig_telemetrysuppress_redundant': 'bool'
    }

    attribute_map = {
        'openconfig_telemetrysuppress_redundant': 'openconfig-telemetry:suppress-redundant'
    }

    def __init__(self, openconfig_telemetrysuppress_redundant=None):  # noqa: E501
        """GetOpenconfigTelemetryTelemetrySystemSubscriptionsPersistentSubscriptionsPersistentSubscriptionSensorProfilesSensorProfileConfigSuppressRedundant - a model defined in Swagger"""  # noqa: E501

        self._openconfig_telemetrysuppress_redundant = None
        self.discriminator = None

        if openconfig_telemetrysuppress_redundant is not None:
            self.openconfig_telemetrysuppress_redundant = openconfig_telemetrysuppress_redundant

    @property
    def openconfig_telemetrysuppress_redundant(self):
        """Gets the openconfig_telemetrysuppress_redundant of this GetOpenconfigTelemetryTelemetrySystemSubscriptionsPersistentSubscriptionsPersistentSubscriptionSensorProfilesSensorProfileConfigSuppressRedundant.  # noqa: E501


        :return: The openconfig_telemetrysuppress_redundant of this GetOpenconfigTelemetryTelemetrySystemSubscriptionsPersistentSubscriptionsPersistentSubscriptionSensorProfilesSensorProfileConfigSuppressRedundant.  # noqa: E501
        :rtype: bool
        """
        return self._openconfig_telemetrysuppress_redundant

    @openconfig_telemetrysuppress_redundant.setter
    def openconfig_telemetrysuppress_redundant(self, openconfig_telemetrysuppress_redundant):
        """Sets the openconfig_telemetrysuppress_redundant of this GetOpenconfigTelemetryTelemetrySystemSubscriptionsPersistentSubscriptionsPersistentSubscriptionSensorProfilesSensorProfileConfigSuppressRedundant.


        :param openconfig_telemetrysuppress_redundant: The openconfig_telemetrysuppress_redundant of this GetOpenconfigTelemetryTelemetrySystemSubscriptionsPersistentSubscriptionsPersistentSubscriptionSensorProfilesSensorProfileConfigSuppressRedundant.  # noqa: E501
        :type: bool
        """

        self._openconfig_telemetrysuppress_redundant = openconfig_telemetrysuppress_redundant

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetOpenconfigTelemetryTelemetrySystemSubscriptionsPersistentSubscriptionsPersistentSubscriptionSensorProfilesSensorProfileConfigSuppressRedundant, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetOpenconfigTelemetryTelemetrySystemSubscriptionsPersistentSubscriptionsPersistentSubscriptionSensorProfilesSensorProfileConfigSuppressRedundant):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
