# SONiC broadview package

BROADVIEW_VERSION = 3.5.0.3
export BROADVIEW_VERSION

SONIC_BROADVIEW = broadview-agent_$(BROADVIEW_VERSION)-1_amd64.deb
$(SONIC_BROADVIEW)_SRC_PATH = $(SRC_PATH)/sonic-broadview
$(SONIC_BROADVIEW)_DEPENDS = $(SWSS) $(LIBSWSSCOMMON) $(LIBSWSSCOMMON_DEV) $(LIBCJSON)
SONIC_MAKE_DEBS += $(SONIC_BROADVIEW)

$(SONIC_BROADVIEW_MGR)_PATH = $(SRC_PATH)/sonic-broadview
