# Docker image for VRRP

DOCKER_VRRP = docker-vrrp.gz
$(DOCKER_VRRP)_PATH = $(DOCKERS_PATH)/docker-vrrp
$(DOCKER_VRRP)_DEPENDS += $(VRRP_PKG)


$(DOCKER_VRRP)_DEPENDS += $(SWSS) $(REDIS_TOOLS)
#$(DOCKER_VRRP)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_STRETCH)_DBG_DEPENDS)
$(DOCKER_VRRP)_DBG_DEPENDS += $(SWSS_DBG) $(LIBSWSSCOMMON_DBG)


#$(DOCKER_VRRP)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE)
$(DOCKER_VRRP)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_STRETCH)

SONIC_DOCKER_IMAGES += $(DOCKER_VRRP)
SONIC_STRETCH_DOCKERS += $(DOCKER_VRRP)

SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_VRRP)


$(DOCKER_VRRP)_CONTAINER_NAME = vrrp
$(DOCKER_VRRP)_RUN_OPT += --net=host --privileged -t
$(DOCKER_VRRP)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_VRRP)_RUN_OPT += -v /host/warmboot:/var/warmboot

#$(DOCKER_VRRP)_BASE_IMAGE_FILES += vrrpd:/usr/bin/vrrpd
