# linuxptp package

LINUXPTP_VERSION_MAJOR = 2.0
LINUXPTP_VERSION_FULL = $(LINUXPTP_VERSION_MAJOR)-1

export LINUXPTP_VERSION_MAJOR LINUXPTP_VERSION_FULL 

LINUXPTP = linuxptp_$(LINUXPTP_VERSION_FULL)_amd64.deb
$(LINUXPTP)_SRC_PATH = $(SRC_PATH)/linuxptp

SONIC_STRETCH_DEBS += $(LINUXPTP)
SONIC_MAKE_DEBS += $(LINUXPTP)
