# netifaces python library

PYTHON_NETIFACES_VERSION = 0.10.9
PYTHON_NETIFACES_PY_VERSION = 2
PYTHON_NETIFACES_PKG_ARCH = amd64

PYTHON_NETIFACES = python-netifaces_$(PYTHON_NETIFACES_VERSION)-1_$(PYTHON_NETIFACES_PKG_ARCH).deb
$(PYTHON_NETIFACES)_SRC_PATH = $(SRC_PATH)/python-netifaces

SONIC_MAKE_DEBS += $(PYTHON_NETIFACES)
SONIC_STRETCH_DEBS += $(PYTHON_NETIFACES)

export PYTHON_NETIFACES
export PYTHON_NETIFACES_VERSION
export PYTHON_NETIFACES_PY_VERSION
