# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_platform_client
from openconfig_platform_client.models.patch_openconfig_platform_components_component_fabric import PatchOpenconfigPlatformComponentsComponentFabric  # noqa: E501
from openconfig_platform_client.rest import ApiException


class TestPatchOpenconfigPlatformComponentsComponentFabric(unittest.TestCase):
    """PatchOpenconfigPlatformComponentsComponentFabric unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchOpenconfigPlatformComponentsComponentFabric(self):
        """Test PatchOpenconfigPlatformComponentsComponentFabric"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_platform_client.models.patch_openconfig_platform_components_component_fabric.PatchOpenconfigPlatformComponentsComponentFabric()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
