# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import sonic_acl_client
from sonic_acl_client.models.sonic_acl_sonic_acl_acl_rule_acl_rule_list_ip_protocol import SonicAclSonicAclAclRuleAclRuleListIpProtocol  # noqa: E501
from sonic_acl_client.rest import ApiException


class TestSonicAclSonicAclAclRuleAclRuleListIpProtocol(unittest.TestCase):
    """SonicAclSonicAclAclRuleAclRuleListIpProtocol unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSonicAclSonicAclAclRuleAclRuleListIpProtocol(self):
        """Test SonicAclSonicAclAclRuleAclRuleListIpProtocol"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sonic_acl_client.models.sonic_acl_sonic_acl_acl_rule_acl_rule_list_ip_protocol.SonicAclSonicAclAclRuleAclRuleListIpProtocol()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
