# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_spanning_tree_client
from openconfig_spanning_tree_client.models.put_openconfig_spanning_tree_stp_rapid_pvst_vlan_interfaces import PutOpenconfigSpanningTreeStpRapidPvstVlanInterfaces  # noqa: E501
from openconfig_spanning_tree_client.rest import ApiException


class TestPutOpenconfigSpanningTreeStpRapidPvstVlanInterfaces(unittest.TestCase):
    """PutOpenconfigSpanningTreeStpRapidPvstVlanInterfaces unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutOpenconfigSpanningTreeStpRapidPvstVlanInterfaces(self):
        """Test PutOpenconfigSpanningTreeStpRapidPvstVlanInterfaces"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_spanning_tree_client.models.put_openconfig_spanning_tree_stp_rapid_pvst_vlan_interfaces.PutOpenconfigSpanningTreeStpRapidPvstVlanInterfaces()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
