# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import sonic_mirror_session_client
from sonic_mirror_session_client.models.put_sonic_mirror_session_sonic_mirror_session_mirror_session import PutSonicMirrorSessionSonicMirrorSessionMirrorSession  # noqa: E501
from sonic_mirror_session_client.rest import ApiException


class TestPutSonicMirrorSessionSonicMirrorSessionMirrorSession(unittest.TestCase):
    """PutSonicMirrorSessionSonicMirrorSessionMirrorSession unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutSonicMirrorSessionSonicMirrorSessionMirrorSession(self):
        """Test PutSonicMirrorSessionSonicMirrorSessionMirrorSession"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sonic_mirror_session_client.models.put_sonic_mirror_session_sonic_mirror_session_mirror_session.PutSonicMirrorSessionSonicMirrorSessionMirrorSession()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
