# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import sonic_acl_client
from sonic_acl_client.models.patch_sonic_acl_sonic_acl_acl_rule_acl_rule_list_src_ipv6 import PatchSonicAclSonicAclAclRuleAclRuleListSrcIpv6  # noqa: E501
from sonic_acl_client.rest import ApiException


class TestPatchSonicAclSonicAclAclRuleAclRuleListSrcIpv6(unittest.TestCase):
    """PatchSonicAclSonicAclAclRuleAclRuleListSrcIpv6 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchSonicAclSonicAclAclRuleAclRuleListSrcIpv6(self):
        """Test PatchSonicAclSonicAclAclRuleAclRuleListSrcIpv6"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sonic_acl_client.models.patch_sonic_acl_sonic_acl_acl_rule_acl_rule_list_src_ipv6.PatchSonicAclSonicAclAclRuleAclRuleListSrcIpv6()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
