# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_lldp_client
from openconfig_lldp_client.models.get_openconfig_lldp_lldp_state_counters_frame_out import GetOpenconfigLldpLldpStateCountersFrameOut  # noqa: E501
from openconfig_lldp_client.rest import ApiException


class TestGetOpenconfigLldpLldpStateCountersFrameOut(unittest.TestCase):
    """GetOpenconfigLldpLldpStateCountersFrameOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOpenconfigLldpLldpStateCountersFrameOut(self):
        """Test GetOpenconfigLldpLldpStateCountersFrameOut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_lldp_client.models.get_openconfig_lldp_lldp_state_counters_frame_out.GetOpenconfigLldpLldpStateCountersFrameOut()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
