# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_interfaces_client
from openconfig_interfaces_client.models.get_openconfig_if_ip_interfaces_interface_routed_vlan_ipv6_config_enabled import GetOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6ConfigEnabled  # noqa: E501
from openconfig_interfaces_client.rest import ApiException


class TestGetOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6ConfigEnabled(unittest.TestCase):
    """GetOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6ConfigEnabled unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6ConfigEnabled(self):
        """Test GetOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6ConfigEnabled"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_interfaces_client.models.get_openconfig_if_ip_interfaces_interface_routed_vlan_ipv6_config_enabled.GetOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6ConfigEnabled()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
