# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_telemetry_client
from openconfig_telemetry_client.models.put_openconfig_telemetry_telemetry_system import PutOpenconfigTelemetryTelemetrySystem  # noqa: E501
from openconfig_telemetry_client.rest import ApiException


class TestPutOpenconfigTelemetryTelemetrySystem(unittest.TestCase):
    """PutOpenconfigTelemetryTelemetrySystem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutOpenconfigTelemetryTelemetrySystem(self):
        """Test PutOpenconfigTelemetryTelemetrySystem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_telemetry_client.models.put_openconfig_telemetry_telemetry_system.PutOpenconfigTelemetryTelemetrySystem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
