# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_spanning_tree_client
from openconfig_spanning_tree_client.models.post_openconfig_spanning_tree_stp_mstp_mst_instances_mst_instance_interfaces_interface_config import PostOpenconfigSpanningTreeStpMstpMstInstancesMstInstanceInterfacesInterfaceConfig  # noqa: E501
from openconfig_spanning_tree_client.rest import ApiException


class TestPostOpenconfigSpanningTreeStpMstpMstInstancesMstInstanceInterfacesInterfaceConfig(unittest.TestCase):
    """PostOpenconfigSpanningTreeStpMstpMstInstancesMstInstanceInterfacesInterfaceConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostOpenconfigSpanningTreeStpMstpMstInstancesMstInstanceInterfacesInterfaceConfig(self):
        """Test PostOpenconfigSpanningTreeStpMstpMstInstancesMstInstanceInterfacesInterfaceConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_spanning_tree_client.models.post_openconfig_spanning_tree_stp_mstp_mst_instances_mst_instance_interfaces_interface_config.PostOpenconfigSpanningTreeStpMstpMstInstancesMstInstanceInterfacesInterfaceConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
