# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_acl_client
from openconfig_acl_client.models.patch_openconfig_acl_acl_acl_sets_acl_set_config import PatchOpenconfigAclAclAclSetsAclSetConfig  # noqa: E501
from openconfig_acl_client.rest import ApiException


class TestPatchOpenconfigAclAclAclSetsAclSetConfig(unittest.TestCase):
    """PatchOpenconfigAclAclAclSetsAclSetConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchOpenconfigAclAclAclSetsAclSetConfig(self):
        """Test PatchOpenconfigAclAclAclSetsAclSetConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_acl_client.models.patch_openconfig_acl_acl_acl_sets_acl_set_config.PatchOpenconfigAclAclAclSetsAclSetConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
