# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import sonic_watermark_telemetry_client
from sonic_watermark_telemetry_client.models.get_sonic_watermark_telemetry_watermark_table import GetSonicWatermarkTelemetryWatermarkTable  # noqa: E501
from sonic_watermark_telemetry_client.rest import ApiException


class TestGetSonicWatermarkTelemetryWatermarkTable(unittest.TestCase):
    """GetSonicWatermarkTelemetryWatermarkTable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSonicWatermarkTelemetryWatermarkTable(self):
        """Test GetSonicWatermarkTelemetryWatermarkTable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sonic_watermark_telemetry_client.models.get_sonic_watermark_telemetry_watermark_table.GetSonicWatermarkTelemetryWatermarkTable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
