# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_interfaces_client
from openconfig_interfaces_client.models.patch_openconfig_if_ip_interfaces_interface_subinterfaces_subinterface_ipv4_addresses import PatchOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv4Addresses  # noqa: E501
from openconfig_interfaces_client.rest import ApiException


class TestPatchOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv4Addresses(unittest.TestCase):
    """PatchOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv4Addresses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv4Addresses(self):
        """Test PatchOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv4Addresses"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_interfaces_client.models.patch_openconfig_if_ip_interfaces_interface_subinterfaces_subinterface_ipv4_addresses.PatchOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv4Addresses()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
