# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_system_client
from openconfig_system_client.models.get_openconfig_system_system_ntp_servers_server_state_offset import GetOpenconfigSystemSystemNtpServersServerStateOffset  # noqa: E501
from openconfig_system_client.rest import ApiException


class TestGetOpenconfigSystemSystemNtpServersServerStateOffset(unittest.TestCase):
    """GetOpenconfigSystemSystemNtpServersServerStateOffset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOpenconfigSystemSystemNtpServersServerStateOffset(self):
        """Test GetOpenconfigSystemSystemNtpServersServerStateOffset"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_system_client.models.get_openconfig_system_system_ntp_servers_server_state_offset.GetOpenconfigSystemSystemNtpServersServerStateOffset()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
