# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_system_client
from openconfig_system_client.models.patch_openconfig_system_system_aaa_authentication_admin_user_config_admin_password import PatchOpenconfigSystemSystemAaaAuthenticationAdminUserConfigAdminPassword  # noqa: E501
from openconfig_system_client.rest import ApiException


class TestPatchOpenconfigSystemSystemAaaAuthenticationAdminUserConfigAdminPassword(unittest.TestCase):
    """PatchOpenconfigSystemSystemAaaAuthenticationAdminUserConfigAdminPassword unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchOpenconfigSystemSystemAaaAuthenticationAdminUserConfigAdminPassword(self):
        """Test PatchOpenconfigSystemSystemAaaAuthenticationAdminUserConfigAdminPassword"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_system_client.models.patch_openconfig_system_system_aaa_authentication_admin_user_config_admin_password.PatchOpenconfigSystemSystemAaaAuthenticationAdminUserConfigAdminPassword()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
