# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_acl_client
from openconfig_acl_client.models.put_openconfig_acl_acl_acl_sets_acl_set_acl_entries_acl_entry_ipv4_config_source_address import PutOpenconfigAclAclAclSetsAclSetAclEntriesAclEntryIpv4ConfigSourceAddress  # noqa: E501
from openconfig_acl_client.rest import ApiException


class TestPutOpenconfigAclAclAclSetsAclSetAclEntriesAclEntryIpv4ConfigSourceAddress(unittest.TestCase):
    """PutOpenconfigAclAclAclSetsAclSetAclEntriesAclEntryIpv4ConfigSourceAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutOpenconfigAclAclAclSetsAclSetAclEntriesAclEntryIpv4ConfigSourceAddress(self):
        """Test PutOpenconfigAclAclAclSetsAclSetAclEntriesAclEntryIpv4ConfigSourceAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_acl_client.models.put_openconfig_acl_acl_acl_sets_acl_set_acl_entries_acl_entry_ipv4_config_source_address.PutOpenconfigAclAclAclSetsAclSetAclEntriesAclEntryIpv4ConfigSourceAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
