# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_interfaces_client
from openconfig_interfaces_client.models.put_openconfig_interfaces_interfaces_interface_config_type import PutOpenconfigInterfacesInterfacesInterfaceConfigType  # noqa: E501
from openconfig_interfaces_client.rest import ApiException


class TestPutOpenconfigInterfacesInterfacesInterfaceConfigType(unittest.TestCase):
    """PutOpenconfigInterfacesInterfacesInterfaceConfigType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutOpenconfigInterfacesInterfacesInterfaceConfigType(self):
        """Test PutOpenconfigInterfacesInterfacesInterfaceConfigType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_interfaces_client.models.put_openconfig_interfaces_interfaces_interface_config_type.PutOpenconfigInterfacesInterfacesInterfaceConfigType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
