# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_acl_client
from openconfig_acl_client.models.get_openconfig_acl_acl_interfaces_interface_egress_acl_sets_egress_acl_set_state import GetOpenconfigAclAclInterfacesInterfaceEgressAclSetsEgressAclSetState  # noqa: E501
from openconfig_acl_client.rest import ApiException


class TestGetOpenconfigAclAclInterfacesInterfaceEgressAclSetsEgressAclSetState(unittest.TestCase):
    """GetOpenconfigAclAclInterfacesInterfaceEgressAclSetsEgressAclSetState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOpenconfigAclAclInterfacesInterfaceEgressAclSetsEgressAclSetState(self):
        """Test GetOpenconfigAclAclInterfacesInterfaceEgressAclSetsEgressAclSetState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_acl_client.models.get_openconfig_acl_acl_interfaces_interface_egress_acl_sets_egress_acl_set_state.GetOpenconfigAclAclInterfacesInterfaceEgressAclSetsEgressAclSetState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
