# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_platform_client
from openconfig_platform_client.models.get_openconfig_platform_components_component_state_memory_utilized import GetOpenconfigPlatformComponentsComponentStateMemoryUtilized  # noqa: E501
from openconfig_platform_client.rest import ApiException


class TestGetOpenconfigPlatformComponentsComponentStateMemoryUtilized(unittest.TestCase):
    """GetOpenconfigPlatformComponentsComponentStateMemoryUtilized unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOpenconfigPlatformComponentsComponentStateMemoryUtilized(self):
        """Test GetOpenconfigPlatformComponentsComponentStateMemoryUtilized"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_platform_client.models.get_openconfig_platform_components_component_state_memory_utilized.GetOpenconfigPlatformComponentsComponentStateMemoryUtilized()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
