# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_interfaces_client
from openconfig_interfaces_client.models.put_openconfig_if_ip_interfaces_interface_subinterfaces_subinterface_ipv6_addresses_address import PutOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6AddressesAddress  # noqa: E501
from openconfig_interfaces_client.rest import ApiException


class TestPutOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6AddressesAddress(unittest.TestCase):
    """PutOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6AddressesAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6AddressesAddress(self):
        """Test PutOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6AddressesAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_interfaces_client.models.put_openconfig_if_ip_interfaces_interface_subinterfaces_subinterface_ipv6_addresses_address.PutOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6AddressesAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
