# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_interfaces_client
from openconfig_interfaces_client.models.post_openconfig_if_ip_interfaces_interface_routed_vlan_ipv4_config_enabled import PostOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv4ConfigEnabled  # noqa: E501
from openconfig_interfaces_client.rest import ApiException


class TestPostOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv4ConfigEnabled(unittest.TestCase):
    """PostOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv4ConfigEnabled unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv4ConfigEnabled(self):
        """Test PostOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv4ConfigEnabled"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_interfaces_client.models.post_openconfig_if_ip_interfaces_interface_routed_vlan_ipv4_config_enabled.PostOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv4ConfigEnabled()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
