# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_acl_client
from openconfig_acl_client.models.put_list_openconfig_acl_acl_interfaces_interface_ingress_acl_sets_ingress_acl_set import PutListOpenconfigAclAclInterfacesInterfaceIngressAclSetsIngressAclSet  # noqa: E501
from openconfig_acl_client.rest import ApiException


class TestPutListOpenconfigAclAclInterfacesInterfaceIngressAclSetsIngressAclSet(unittest.TestCase):
    """PutListOpenconfigAclAclInterfacesInterfaceIngressAclSetsIngressAclSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutListOpenconfigAclAclInterfacesInterfaceIngressAclSetsIngressAclSet(self):
        """Test PutListOpenconfigAclAclInterfacesInterfaceIngressAclSetsIngressAclSet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_acl_client.models.put_list_openconfig_acl_acl_interfaces_interface_ingress_acl_sets_ingress_acl_set.PutListOpenconfigAclAclInterfacesInterfaceIngressAclSetsIngressAclSet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
