# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_telemetry_client
from openconfig_telemetry_client.models.put_openconfig_telemetry_telemetry_system_sensor_groups_sensor_group_sensor_paths_sensor_path import PutOpenconfigTelemetryTelemetrySystemSensorGroupsSensorGroupSensorPathsSensorPath  # noqa: E501
from openconfig_telemetry_client.rest import ApiException


class TestPutOpenconfigTelemetryTelemetrySystemSensorGroupsSensorGroupSensorPathsSensorPath(unittest.TestCase):
    """PutOpenconfigTelemetryTelemetrySystemSensorGroupsSensorGroupSensorPathsSensorPath unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutOpenconfigTelemetryTelemetrySystemSensorGroupsSensorGroupSensorPathsSensorPath(self):
        """Test PutOpenconfigTelemetryTelemetrySystemSensorGroupsSensorGroupSensorPathsSensorPath"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_telemetry_client.models.put_openconfig_telemetry_telemetry_system_sensor_groups_sensor_group_sensor_paths_sensor_path.PutOpenconfigTelemetryTelemetrySystemSensorGroupsSensorGroupSensorPathsSensorPath()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
