# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_interfaces_client
from openconfig_interfaces_client.models.openconfig_if_ip_interfaces_interface_subinterfaces_subinterface_ipv6_config_mtu import OpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6ConfigMtu  # noqa: E501
from openconfig_interfaces_client.rest import ApiException


class TestOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6ConfigMtu(unittest.TestCase):
    """OpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6ConfigMtu unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6ConfigMtu(self):
        """Test OpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6ConfigMtu"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_interfaces_client.models.openconfig_if_ip_interfaces_interface_subinterfaces_subinterface_ipv6_config_mtu.OpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6ConfigMtu()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
