# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_system_client
from openconfig_system_client.models.get_openconfig_system_system_cpus_cpu_state_software_interrupt_max import GetOpenconfigSystemSystemCpusCpuStateSoftwareInterruptMax  # noqa: E501
from openconfig_system_client.rest import ApiException


class TestGetOpenconfigSystemSystemCpusCpuStateSoftwareInterruptMax(unittest.TestCase):
    """GetOpenconfigSystemSystemCpusCpuStateSoftwareInterruptMax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOpenconfigSystemSystemCpusCpuStateSoftwareInterruptMax(self):
        """Test GetOpenconfigSystemSystemCpusCpuStateSoftwareInterruptMax"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_system_client.models.get_openconfig_system_system_cpus_cpu_state_software_interrupt_max.GetOpenconfigSystemSystemCpusCpuStateSoftwareInterruptMax()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
