# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_acl_client
from openconfig_acl_client.models.get_openconfig_acl_acl_acl_sets_acl_set_acl_entries_acl_entry_ipv4_config_protocol import GetOpenconfigAclAclAclSetsAclSetAclEntriesAclEntryIpv4ConfigProtocol  # noqa: E501
from openconfig_acl_client.rest import ApiException


class TestGetOpenconfigAclAclAclSetsAclSetAclEntriesAclEntryIpv4ConfigProtocol(unittest.TestCase):
    """GetOpenconfigAclAclAclSetsAclSetAclEntriesAclEntryIpv4ConfigProtocol unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOpenconfigAclAclAclSetsAclSetAclEntriesAclEntryIpv4ConfigProtocol(self):
        """Test GetOpenconfigAclAclAclSetsAclSetAclEntriesAclEntryIpv4ConfigProtocol"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_acl_client.models.get_openconfig_acl_acl_acl_sets_acl_set_acl_entries_acl_entry_ipv4_config_protocol.GetOpenconfigAclAclAclSetsAclSetAclEntriesAclEntryIpv4ConfigProtocol()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
