# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_interfaces_client
from openconfig_interfaces_client.models.openconfig_interfaces_interfaces_openconfiginterfacesinterfaces_subinterfaces_openconfigifipipv6_addresses_vrrp_vrrpgroup import OpenconfigInterfacesInterfacesOpenconfiginterfacesinterfacesSubinterfacesOpenconfigifipipv6AddressesVrrpVrrpgroup  # noqa: E501
from openconfig_interfaces_client.rest import ApiException


class TestOpenconfigInterfacesInterfacesOpenconfiginterfacesinterfacesSubinterfacesOpenconfigifipipv6AddressesVrrpVrrpgroup(unittest.TestCase):
    """OpenconfigInterfacesInterfacesOpenconfiginterfacesinterfacesSubinterfacesOpenconfigifipipv6AddressesVrrpVrrpgroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpenconfigInterfacesInterfacesOpenconfiginterfacesinterfacesSubinterfacesOpenconfigifipipv6AddressesVrrpVrrpgroup(self):
        """Test OpenconfigInterfacesInterfacesOpenconfiginterfacesinterfacesSubinterfacesOpenconfigifipipv6AddressesVrrpVrrpgroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_interfaces_client.models.openconfig_interfaces_interfaces_openconfiginterfacesinterfaces_subinterfaces_openconfigifipipv6_addresses_vrrp_vrrpgroup.OpenconfigInterfacesInterfacesOpenconfiginterfacesinterfacesSubinterfacesOpenconfigifipipv6AddressesVrrpVrrpgroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
