# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_interfaces_client
from openconfig_interfaces_client.models.openconfig_if_ip_interfaces_interface_routed_vlan_ipv4_neighbors import OpenconfigIfIpInterfacesInterfaceRoutedVlanIpv4Neighbors  # noqa: E501
from openconfig_interfaces_client.rest import ApiException


class TestOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv4Neighbors(unittest.TestCase):
    """OpenconfigIfIpInterfacesInterfaceRoutedVlanIpv4Neighbors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv4Neighbors(self):
        """Test OpenconfigIfIpInterfacesInterfaceRoutedVlanIpv4Neighbors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_interfaces_client.models.openconfig_if_ip_interfaces_interface_routed_vlan_ipv4_neighbors.OpenconfigIfIpInterfacesInterfaceRoutedVlanIpv4Neighbors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
