# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_interfaces_client
from openconfig_interfaces_client.models.put_openconfig_if_ip_interfaces_interface_subinterfaces_subinterface_ipv4_config_dhcp_client import PutOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv4ConfigDhcpClient  # noqa: E501
from openconfig_interfaces_client.rest import ApiException


class TestPutOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv4ConfigDhcpClient(unittest.TestCase):
    """PutOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv4ConfigDhcpClient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv4ConfigDhcpClient(self):
        """Test PutOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv4ConfigDhcpClient"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_interfaces_client.models.put_openconfig_if_ip_interfaces_interface_subinterfaces_subinterface_ipv4_config_dhcp_client.PutOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv4ConfigDhcpClient()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
