# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_interfaces_client
from openconfig_interfaces_client.models.put_openconfig_if_ip_interfaces_interface_routed_vlan_ipv6_addresses_address_vrrp_vrrp_group_config_preempt import PutOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6AddressesAddressVrrpVrrpGroupConfigPreempt  # noqa: E501
from openconfig_interfaces_client.rest import ApiException


class TestPutOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6AddressesAddressVrrpVrrpGroupConfigPreempt(unittest.TestCase):
    """PutOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6AddressesAddressVrrpVrrpGroupConfigPreempt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6AddressesAddressVrrpVrrpGroupConfigPreempt(self):
        """Test PutOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6AddressesAddressVrrpVrrpGroupConfigPreempt"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_interfaces_client.models.put_openconfig_if_ip_interfaces_interface_routed_vlan_ipv6_addresses_address_vrrp_vrrp_group_config_preempt.PutOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6AddressesAddressVrrpVrrpGroupConfigPreempt()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
