# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_interfaces_client
from openconfig_interfaces_client.models.get_openconfig_if_ip_interfaces_interface_subinterfaces_subinterface_ipv6_unnumbered_interface_ref_config_subinterface import GetOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6UnnumberedInterfaceRefConfigSubinterface  # noqa: E501
from openconfig_interfaces_client.rest import ApiException


class TestGetOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6UnnumberedInterfaceRefConfigSubinterface(unittest.TestCase):
    """GetOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6UnnumberedInterfaceRefConfigSubinterface unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6UnnumberedInterfaceRefConfigSubinterface(self):
        """Test GetOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6UnnumberedInterfaceRefConfigSubinterface"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_interfaces_client.models.get_openconfig_if_ip_interfaces_interface_subinterfaces_subinterface_ipv6_unnumbered_interface_ref_config_subinterface.GetOpenconfigIfIpInterfacesInterfaceSubinterfacesSubinterfaceIpv6UnnumberedInterfaceRefConfigSubinterface()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
