# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_system_client
from openconfig_system_client.models.openconfig_system_system_openconfigsystemsystem_aaa_authentication_adminuser_config import OpenconfigSystemSystemOpenconfigsystemsystemAaaAuthenticationAdminuserConfig  # noqa: E501
from openconfig_system_client.rest import ApiException


class TestOpenconfigSystemSystemOpenconfigsystemsystemAaaAuthenticationAdminuserConfig(unittest.TestCase):
    """OpenconfigSystemSystemOpenconfigsystemsystemAaaAuthenticationAdminuserConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpenconfigSystemSystemOpenconfigsystemsystemAaaAuthenticationAdminuserConfig(self):
        """Test OpenconfigSystemSystemOpenconfigsystemsystemAaaAuthenticationAdminuserConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_system_client.models.openconfig_system_system_openconfigsystemsystem_aaa_authentication_adminuser_config.OpenconfigSystemSystemOpenconfigsystemsystemAaaAuthenticationAdminuserConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
