# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_telemetry_client
from openconfig_telemetry_client.models.openconfig_telemetry_telemetry_system_openconfigtelemetrytelemetrysystem_sensorgroups_sensorgroup import OpenconfigTelemetryTelemetrySystemOpenconfigtelemetrytelemetrysystemSensorgroupsSensorgroup  # noqa: E501
from openconfig_telemetry_client.rest import ApiException


class TestOpenconfigTelemetryTelemetrySystemOpenconfigtelemetrytelemetrysystemSensorgroupsSensorgroup(unittest.TestCase):
    """OpenconfigTelemetryTelemetrySystemOpenconfigtelemetrytelemetrysystemSensorgroupsSensorgroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpenconfigTelemetryTelemetrySystemOpenconfigtelemetrytelemetrysystemSensorgroupsSensorgroup(self):
        """Test OpenconfigTelemetryTelemetrySystemOpenconfigtelemetrytelemetrysystemSensorgroupsSensorgroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_telemetry_client.models.openconfig_telemetry_telemetry_system_openconfigtelemetrytelemetrysystem_sensorgroups_sensorgroup.OpenconfigTelemetryTelemetrySystemOpenconfigtelemetrytelemetrysystemSensorgroupsSensorgroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
