# coding: utf-8

"""
    SONiC Management Infra PoC - VLANs

    Sample OpenAPI spec for SONiC VLAN table operations.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: noone@broadcom.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import vlan_client
from vlan_client.models.vlan_info import VlanInfo  # noqa: E501
from vlan_client.rest import ApiException


class TestVlanInfo(unittest.TestCase):
    """VlanInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVlanInfo(self):
        """Test VlanInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vlan_client.models.vlan_info.VlanInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
