# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_interfaces_client
from openconfig_interfaces_client.models.get_openconfig_if_ip_interfaces_interface_routed_vlan_ipv6_addresses_address_vrrp_vrrp_group_state_virtual_router_id import GetOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6AddressesAddressVrrpVrrpGroupStateVirtualRouterId  # noqa: E501
from openconfig_interfaces_client.rest import ApiException


class TestGetOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6AddressesAddressVrrpVrrpGroupStateVirtualRouterId(unittest.TestCase):
    """GetOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6AddressesAddressVrrpVrrpGroupStateVirtualRouterId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6AddressesAddressVrrpVrrpGroupStateVirtualRouterId(self):
        """Test GetOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6AddressesAddressVrrpVrrpGroupStateVirtualRouterId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_interfaces_client.models.get_openconfig_if_ip_interfaces_interface_routed_vlan_ipv6_addresses_address_vrrp_vrrp_group_state_virtual_router_id.GetOpenconfigIfIpInterfacesInterfaceRoutedVlanIpv6AddressesAddressVrrpVrrpGroupStateVirtualRouterId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
