# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openconfig_interfaces_client
from openconfig_interfaces_client.models.post_openconfig_vlan_interfaces_interface_aggregation_switched_vlan_config import PostOpenconfigVlanInterfacesInterfaceAggregationSwitchedVlanConfig  # noqa: E501
from openconfig_interfaces_client.rest import ApiException


class TestPostOpenconfigVlanInterfacesInterfaceAggregationSwitchedVlanConfig(unittest.TestCase):
    """PostOpenconfigVlanInterfacesInterfaceAggregationSwitchedVlanConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostOpenconfigVlanInterfacesInterfaceAggregationSwitchedVlanConfig(self):
        """Test PostOpenconfigVlanInterfacesInterfaceAggregationSwitchedVlanConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openconfig_interfaces_client.models.post_openconfig_vlan_interfaces_interface_aggregation_switched_vlan_config.PostOpenconfigVlanInterfacesInterfaceAggregationSwitchedVlanConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
