# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import sonic_interface_client
from sonic_interface_client.models.sonic_interface_sonic_interface_interface_interface_ipaddr_list import SonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList  # noqa: E501
from sonic_interface_client.rest import ApiException


class TestSonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList(unittest.TestCase):
    """SonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList(self):
        """Test SonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sonic_interface_client.models.sonic_interface_sonic_interface_interface_interface_ipaddr_list.SonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
