# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import sonic_port_client
from sonic_port_client.api.sonic_port_api import SonicPortApi  # noqa: E501
from sonic_port_client.rest import ApiException


class TestSonicPortApi(unittest.TestCase):
    """SonicPortApi unit test stubs"""

    def setUp(self):
        self.api = sonic_port_client.api.sonic_port_api.SonicPortApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_list_sonic_port_sonic_port_port_port_list(self):
        """Test case for delete_list_sonic_port_sonic_port_port_port_list

        """
        pass

    def test_delete_sonic_port_sonic_port(self):
        """Test case for delete_sonic_port_sonic_port

        """
        pass

    def test_delete_sonic_port_sonic_port_port(self):
        """Test case for delete_sonic_port_sonic_port_port

        """
        pass

    def test_delete_sonic_port_sonic_port_port_port_list(self):
        """Test case for delete_sonic_port_sonic_port_port_port_list

        """
        pass

    def test_delete_sonic_port_sonic_port_port_port_list_admin_status(self):
        """Test case for delete_sonic_port_sonic_port_port_port_list_admin_status

        """
        pass

    def test_delete_sonic_port_sonic_port_port_port_list_alias(self):
        """Test case for delete_sonic_port_sonic_port_port_port_list_alias

        """
        pass

    def test_delete_sonic_port_sonic_port_port_port_list_description(self):
        """Test case for delete_sonic_port_sonic_port_port_port_list_description

        """
        pass

    def test_delete_sonic_port_sonic_port_port_port_list_index(self):
        """Test case for delete_sonic_port_sonic_port_port_port_list_index

        """
        pass

    def test_delete_sonic_port_sonic_port_port_port_list_lanes(self):
        """Test case for delete_sonic_port_sonic_port_port_port_list_lanes

        """
        pass

    def test_delete_sonic_port_sonic_port_port_port_list_mtu(self):
        """Test case for delete_sonic_port_sonic_port_port_port_list_mtu

        """
        pass

    def test_delete_sonic_port_sonic_port_port_port_list_speed(self):
        """Test case for delete_sonic_port_sonic_port_port_port_list_speed

        """
        pass

    def test_delete_sonic_port_sonic_port_port_port_list_valid_speeds(self):
        """Test case for delete_sonic_port_sonic_port_port_port_list_valid_speeds

        """
        pass

    def test_get_list_sonic_port_sonic_port_port_port_list(self):
        """Test case for get_list_sonic_port_sonic_port_port_port_list

        """
        pass

    def test_get_sonic_port_sonic_port(self):
        """Test case for get_sonic_port_sonic_port

        """
        pass

    def test_get_sonic_port_sonic_port_port(self):
        """Test case for get_sonic_port_sonic_port_port

        """
        pass

    def test_get_sonic_port_sonic_port_port_port_list(self):
        """Test case for get_sonic_port_sonic_port_port_port_list

        """
        pass

    def test_get_sonic_port_sonic_port_port_port_list_admin_status(self):
        """Test case for get_sonic_port_sonic_port_port_port_list_admin_status

        """
        pass

    def test_get_sonic_port_sonic_port_port_port_list_alias(self):
        """Test case for get_sonic_port_sonic_port_port_port_list_alias

        """
        pass

    def test_get_sonic_port_sonic_port_port_port_list_description(self):
        """Test case for get_sonic_port_sonic_port_port_port_list_description

        """
        pass

    def test_get_sonic_port_sonic_port_port_port_list_index(self):
        """Test case for get_sonic_port_sonic_port_port_port_list_index

        """
        pass

    def test_get_sonic_port_sonic_port_port_port_list_lanes(self):
        """Test case for get_sonic_port_sonic_port_port_port_list_lanes

        """
        pass

    def test_get_sonic_port_sonic_port_port_port_list_mtu(self):
        """Test case for get_sonic_port_sonic_port_port_port_list_mtu

        """
        pass

    def test_get_sonic_port_sonic_port_port_port_list_speed(self):
        """Test case for get_sonic_port_sonic_port_port_port_list_speed

        """
        pass

    def test_get_sonic_port_sonic_port_port_port_list_valid_speeds(self):
        """Test case for get_sonic_port_sonic_port_port_port_list_valid_speeds

        """
        pass

    def test_patch_list_sonic_port_sonic_port_port_port_list(self):
        """Test case for patch_list_sonic_port_sonic_port_port_port_list

        """
        pass

    def test_patch_sonic_port_sonic_port(self):
        """Test case for patch_sonic_port_sonic_port

        """
        pass

    def test_patch_sonic_port_sonic_port_port(self):
        """Test case for patch_sonic_port_sonic_port_port

        """
        pass

    def test_patch_sonic_port_sonic_port_port_port_list(self):
        """Test case for patch_sonic_port_sonic_port_port_port_list

        """
        pass

    def test_patch_sonic_port_sonic_port_port_port_list_admin_status(self):
        """Test case for patch_sonic_port_sonic_port_port_port_list_admin_status

        """
        pass

    def test_patch_sonic_port_sonic_port_port_port_list_alias(self):
        """Test case for patch_sonic_port_sonic_port_port_port_list_alias

        """
        pass

    def test_patch_sonic_port_sonic_port_port_port_list_description(self):
        """Test case for patch_sonic_port_sonic_port_port_port_list_description

        """
        pass

    def test_patch_sonic_port_sonic_port_port_port_list_index(self):
        """Test case for patch_sonic_port_sonic_port_port_port_list_index

        """
        pass

    def test_patch_sonic_port_sonic_port_port_port_list_lanes(self):
        """Test case for patch_sonic_port_sonic_port_port_port_list_lanes

        """
        pass

    def test_patch_sonic_port_sonic_port_port_port_list_mtu(self):
        """Test case for patch_sonic_port_sonic_port_port_port_list_mtu

        """
        pass

    def test_patch_sonic_port_sonic_port_port_port_list_speed(self):
        """Test case for patch_sonic_port_sonic_port_port_port_list_speed

        """
        pass

    def test_patch_sonic_port_sonic_port_port_port_list_valid_speeds(self):
        """Test case for patch_sonic_port_sonic_port_port_port_list_valid_speeds

        """
        pass

    def test_post_list_sonic_port_sonic_port_port_port_list(self):
        """Test case for post_list_sonic_port_sonic_port_port_port_list

        """
        pass

    def test_post_sonic_port_sonic_port_port(self):
        """Test case for post_sonic_port_sonic_port_port

        """
        pass

    def test_post_sonic_port_sonic_port_port_port_list_index(self):
        """Test case for post_sonic_port_sonic_port_port_port_list_index

        """
        pass

    def test_put_list_sonic_port_sonic_port_port_port_list(self):
        """Test case for put_list_sonic_port_sonic_port_port_port_list

        """
        pass

    def test_put_sonic_port_sonic_port(self):
        """Test case for put_sonic_port_sonic_port

        """
        pass

    def test_put_sonic_port_sonic_port_port(self):
        """Test case for put_sonic_port_sonic_port_port

        """
        pass

    def test_put_sonic_port_sonic_port_port_port_list(self):
        """Test case for put_sonic_port_sonic_port_port_port_list

        """
        pass

    def test_put_sonic_port_sonic_port_port_port_list_admin_status(self):
        """Test case for put_sonic_port_sonic_port_port_port_list_admin_status

        """
        pass

    def test_put_sonic_port_sonic_port_port_port_list_alias(self):
        """Test case for put_sonic_port_sonic_port_port_port_list_alias

        """
        pass

    def test_put_sonic_port_sonic_port_port_port_list_description(self):
        """Test case for put_sonic_port_sonic_port_port_port_list_description

        """
        pass

    def test_put_sonic_port_sonic_port_port_port_list_index(self):
        """Test case for put_sonic_port_sonic_port_port_port_list_index

        """
        pass

    def test_put_sonic_port_sonic_port_port_port_list_lanes(self):
        """Test case for put_sonic_port_sonic_port_port_port_list_lanes

        """
        pass

    def test_put_sonic_port_sonic_port_port_port_list_mtu(self):
        """Test case for put_sonic_port_sonic_port_port_port_list_mtu

        """
        pass

    def test_put_sonic_port_sonic_port_port_port_list_speed(self):
        """Test case for put_sonic_port_sonic_port_port_port_list_speed

        """
        pass

    def test_put_sonic_port_sonic_port_port_port_list_valid_speeds(self):
        """Test case for put_sonic_port_sonic_port_port_port_list_valid_speeds

        """
        pass


if __name__ == '__main__':
    unittest.main()
