# coding: utf-8

"""
    Sonic Network Management APIs

    Network management Open APIs for Sonic.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import sonic_port_client
from sonic_port_client.models.get_sonic_port_sonic_port_port_port_list_speed import GetSonicPortSonicPortPortPortListSpeed  # noqa: E501
from sonic_port_client.rest import ApiException


class TestGetSonicPortSonicPortPortPortListSpeed(unittest.TestCase):
    """GetSonicPortSonicPortPortPortListSpeed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSonicPortSonicPortPortPortListSpeed(self):
        """Test GetSonicPortSonicPortPortPortListSpeed"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sonic_port_client.models.get_sonic_port_sonic_port_port_port_list_speed.GetSonicPortSonicPortPortPortListSpeed()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
